<script>
 import { onMount } from 'svelte'; import { SlidersHorizontal, CalendarClock, Check } from 'lucide-svelte'; import { api } from '../api.js';
 let preferences=$state({language:'English',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,units:'SI',response_style:'concise',personal_instructions:''}),settings=$state({reminder_mode:'suggest',memory_mode:'suggest',organization_mode:'suggest',daily_checkin_enabled:false,daily_checkin_time:'17:00',reminder_hour:13});
 let loading=$state(true),busy=$state(false),error=$state(''),notice=$state('');
 onMount(async()=>{try{[preferences,settings]=await Promise.all([api('/preferences'),api('/personal/settings')]);}catch(e){error=e.message;}finally{loading=false;}});
 async function save(event){event.preventDefault();busy=true;error='';notice='';try{await api('/preferences',{method:'PATCH',body:{language:preferences.language,timezone:preferences.timezone,units:preferences.units,response_style:preferences.response_style,personal_instructions:preferences.personal_instructions}});await api('/personal/settings',{method:'PATCH',body:{reminder_mode:settings.reminder_mode,memory_mode:settings.memory_mode,organization_mode:settings.organization_mode,daily_checkin_enabled:settings.daily_checkin_enabled,daily_checkin_time:settings.daily_checkin_time,reminder_hour:Number(settings.reminder_hour)}});notice='Your assistant preferences have been saved.';}catch(e){error=e.message;}finally{busy=false;}}
</script>
{#if error}<div class="banner error" role="alert">{error}</div>{/if}{#if notice}<div class="banner success" role="status"><Check size={16}/>{notice}</div>{/if}
{#if loading}<p class="muted">Loading preferences…</p>{:else}<form onsubmit={save} class="settings-layout"><section class="card"><div class="section-heading"><h2><SlidersHorizontal size={20}/>How Optimus responds</h2></div><div class="form-grid"><label>Language<input bind:value={preferences.language} placeholder="English" required/></label><label>Timezone<input bind:value={preferences.timezone} placeholder="Asia/Kolkata" required/></label><label>Units<select bind:value={preferences.units}><option value="SI">SI</option><option value="Imperial">Imperial</option><option value="source">Preserve source units</option></select></label><label>Response style<select bind:value={preferences.response_style}><option value="concise">Concise</option><option value="detailed">Detailed</option><option value="technical">Technical</option><option value="plain_language">Plain language</option></select></label></div><label>Personal instructions<textarea bind:value={preferences.personal_instructions} rows="5" placeholder="My role, terminology I use, and how I prefer to work…"></textarea><small class="help">These instructions help your personal assistant. Workspace policy and access permissions continue to apply.</small></label></section>
<section class="card"><div class="section-heading"><h2><CalendarClock size={20}/>Proactive assistance</h2></div><div class="form-grid"><label>Suggested reminders<select bind:value={settings.reminder_mode}><option value="suggest">Ask me to review</option><option value="automatic">Create automatically with Undo</option><option value="off">Off</option></select></label><label>Remembered context<select bind:value={settings.memory_mode}><option value="suggest">Ask me to review</option><option value="automatic">Save automatically with Undo</option><option value="off">Off</option></select></label><label>Weekly organization<select bind:value={settings.organization_mode}><option value="suggest">Review suggestions</option><option value="automatic">Apply automatically with history</option><option value="off">Off</option></select></label><label>Preferred reminder hour<input type="number" min="0" max="23" bind:value={settings.reminder_hour}/></label></div><label class="check-row"><input type="checkbox" bind:checked={settings.daily_checkin_enabled}/><span>Invite me to a daily five-minute check-in</span></label><label>Check-in time<input type="time" bind:value={settings.daily_checkin_time}/><small class="help">Uses your timezone. A prompt opens the in-app conversation; it does not initiate a phone call.</small></label></section><div class="form-actions"><button class="button primary" disabled={busy}>{busy?'Saving…':'Save preferences'}</button></div></form>{/if}
