<script>
 import { onMount } from 'svelte'; import { Undo2, RefreshCw, FolderTree, Activity } from 'lucide-svelte'; import { api } from '../api.js';
 let actions=$state([]),preview=$state(null),busy=$state(false),error=$state(''),notice=$state('');
 onMount(load);
 async function load(){try{actions=await api('/personal/actions');}catch(e){error=e.message;}}
 async function undo(a){busy=true;error='';try{await api(`/personal/actions/${a.id}/undo`,{method:'POST',body:{}});notice='Action reversed.';await load();}catch(e){error=e.message;}finally{busy=false;}}
 async function organize(){busy=true;error='';try{preview=await api('/personal/organization/preview',{method:'POST',body:{}});}catch(e){error=e.message;}finally{busy=false;}}
 async function apply(){busy=true;error='';try{await api(`/personal/organization/${preview.id}/apply`,{method:'POST',body:{}});preview=null;notice='Organization applied. Original notes were retained.';await load();}catch(e){error=e.message;}finally{busy=false;}}
</script>
{#if error}<div class="banner error" role="alert">{error}</div>{/if}{#if notice}<div class="banner success" role="status">{notice}</div>{/if}
<section class="card organization-card"><span class="feature-icon"><FolderTree size={24}/></span><div class="grow"><h2>Keep your notebook organized</h2><p class="help">Review suggested filing changes before applying them. Your original notes and deadlines stay intact.</p></div><button class="button" onclick={organize} disabled={busy}>{busy?'Working…':'Preview organization'}</button></section>
{#if preview}<section class="card"><h2>Proposed organization</h2><div class="compact-list">{#each preview.moves||[] as move}<article><FolderTree size={16}/><div><strong>{move.title}</strong><small>File under {move.folder_name}</small></div></article>{:else}<p class="help">Everything is already filed. No changes are proposed.</p>{/each}</div><div class="form-actions"><button class="button" onclick={()=>preview=null}>Dismiss</button><button class="button primary" onclick={apply} disabled={busy}>Apply organization</button></div></section>{/if}
<div class="section-heading"><h2>Assistant activity</h2><button class="text-button" onclick={load}><RefreshCw size={15}/>Refresh</button></div><div class="stack">{#each actions as action}<article class="card row-card"><span class="feature-icon"><Activity size={20}/></span><div class="grow"><h3>{action.title||action.kind?.replaceAll('_',' ')}</h3><p class="help">{action.description||action.summary||''}</p><small class="muted">{new Date(action.created_at).toLocaleString()}</small></div><span class="tag">{action.status}</span>{#if !['undone','failed','cancelled'].includes(action.status)&&action.reversible!==false}<button class="button" onclick={()=>undo(action)} disabled={busy}><Undo2 size={15}/>Undo</button>{/if}</article>{:else}<div class="empty card"><Activity size={28}/><h2>No automatic changes yet.</h2><p>Captures, reminders, and filing changes appear here.</p></div>{/each}</div>
