<script>
 import { onMount } from 'svelte';import { CalendarDays, Cable, Database, Video, Mail, RefreshCw, Trash2, ExternalLink, Check, Plus } from 'lucide-svelte';import { api, query } from '../api.js';import DeliveryPanel from './DeliveryPanel.svelte';
 let { workspaceId=null,canManage=true,isAdmin=false }=$props();
 let rows=$state([]),capabilities=$state(null),events=$state([]),resources=$state({}),editing=$state(null),provider=$state('influxdb'),name=$state(''),url=$state(''),token=$state(''),orgId=$state(''),buckets=$state(''),accountId=$state(''),clientId=$state(''),clientSecret=$state(''),allowPrivate=$state(false),busy=$state(false),error=$state(''),notice=$state(''),includeTranscripts=$state(false);
 const icons={microsoft:CalendarDays,influxdb:Database,zoom:Video,teams_workflow:Mail};
 onMount(load);
 async function load(){try{const [all,caps]=await Promise.all([api('/connections'+query({workspace_id:workspaceId})),api('/connections/capabilities')]);rows=all.filter(c=>workspaceId?c.workspace_id===workspaceId:!c.workspace_id);capabilities=caps;if(!workspaceId){const end=new Date(Date.now()+7*86400000);events=await api('/calendar/events'+query({start:new Date().toISOString(),end:end.toISOString()}));}}catch(e){error=e.message;}}
 async function microsoft(){busy=true;error='';try{const r=await api('/connections/microsoft/start',{method:'POST',body:{include_transcripts:includeTranscripts}});window.location.assign(r.authorization_url);}catch(e){error=e.message;}finally{busy=false;}}
 function add(p){provider=p;editing='new';name=p==='influxdb'?'Plant historian':p==='zoom'?'Zoom meeting artifacts':'Teams notifications';url='';token='';orgId='';buckets='';accountId='';clientId='';clientSecret='';allowPrivate=false;}
 async function save(event){event.preventDefault();busy=true;error='';try{const c=provider==='influxdb'?{url,org_id:orgId,bucket_ids:buckets.split(',').map(v=>v.trim()).filter(Boolean),allow_private_network:allowPrivate}:provider==='teams_workflow'?{}:{};const credentials=provider==='teams_workflow'?{webhook_url:url}:provider==='zoom'?{account_id:accountId,client_id:clientId,client_secret:clientSecret}:{token};await api('/connections',{method:'POST',body:{provider,name,workspace_id:workspaceId,config:c,credentials}});editing=null;notice='Connection saved. Test access and select its resources.';await load();}catch(e){error=e.message;}finally{busy=false;}}
 async function inspect(c){busy=true;error='';try{resources={...resources,[c.id]:await api(`/connections/${c.id}/resources`)};await load();}catch(e){error=e.message;}finally{busy=false;}}
 async function sync(c){busy=true;error='';try{const r=await api(`/connections/${c.id}/sync`,{method:'POST',body:{}});notice=r.message||'Synchronization completed.';await load();}catch(e){error=e.message;}finally{busy=false;}}
 async function disconnect(c){if(!confirm(`Disconnect ${c.name}?`))return;busy=true;try{await api(`/connections/${c.id}`,{method:'DELETE'});notice='Connection disconnected.';await load();}catch(e){error=e.message;}finally{busy=false;}}
 async function chooseCalendar(c,id,enabled){const old=c.config?.calendar_ids||[];const calendarIds=enabled?[...new Set([...old,id])]:old.filter(v=>v!==id);try{await api(`/connections/${c.id}`,{method:'PATCH',body:{config:{calendar_ids:calendarIds}}});await load();}catch(e){error=e.message;}}
  async function updateResources(connection,config){busy=true;error='';try{await api(`/connections/${connection.id}`,{method:'PATCH',body:{config}});await load();notice='Resource selection saved.';}catch(e){error=e.message;}finally{busy=false;}}
</script>
{#if error}<div class="banner error" role="alert">{error}</div>{/if}{#if notice}<div class="banner success" role="status"><Check size={16}/>{notice}</div>{/if}
<div class="info-strip"><Cable size={20}/><p>{workspaceId?'Workspace connections are available only through permitted tools. Industrial integrations read data; they do not issue PLC commands.':'Connect your calendar and meeting sources. Source credentials stay on the server and are never included in model prompts.'}</p></div>
{#if canManage}<div class="connection-catalog">{#if !workspaceId}<article class="card"><span class="feature-icon"><CalendarDays size={25}/></span><h2>Microsoft 365</h2><p>Outlook calendar and eligible Teams meeting transcripts.</p><label class="check-row"><input type="checkbox" bind:checked={includeTranscripts}/><span>Also request meeting transcript access</span></label><button class="button primary" onclick={microsoft} disabled={busy||!capabilities?.microsoft?.configured}><ExternalLink size={15}/>Connect Outlook</button><small class="help">Your administrator must configure Microsoft OAuth first. Transcript permissions may require tenant approval.</small></article>{/if}{#if workspaceId}<article class="card"><span class="feature-icon"><Database size={25}/></span><h2>InfluxDB</h2><p>Read approved measurements from explicitly selected organizations and buckets.</p><button class="button" onclick={()=>add('influxdb')} disabled={!isAdmin}><Plus size={15}/>Add data connection</button><small class="help">Use a read-only token limited to the required buckets. An installation administrator configures this source.</small></article>{/if}<article class="card"><span class="feature-icon"><Video size={25}/></span><h2>Zoom artifacts</h2><p>Access eligible recording transcripts through a configured Zoom integration.</p><button class="button" onclick={()=>add('zoom')} disabled={!isAdmin}><Plus size={15}/>Configure Zoom</button><small class="help">You can also import minutes or a transcript directly in a Meeting Room.</small></article><article class="card"><span class="feature-icon"><Mail size={25}/></span><h2>Teams delivery</h2><p>Send approved notifications through a Teams Workflow endpoint.</p><button class="button" onclick={()=>add('teams_workflow')}><Plus size={15}/>Add Teams Workflow</button><small class="help">Email delivery uses the installation SMTP configuration.</small></article></div>{/if}
{#if editing}<section class="card connection-editor"><h2>Configure {provider==='influxdb'?'InfluxDB':provider==='zoom'?'Zoom':'Teams delivery'}</h2><form onsubmit={save}><label>Connection name<input bind:value={name} required/></label>{#if provider==='influxdb'}<div class="form-grid"><label>Server URL<input type="url" bind:value={url} placeholder="https://influx.example.com" required/></label><label>Organization ID<input bind:value={orgId} placeholder="Choose after testing, or enter ID"/></label></div><label class="check-row"><input type="checkbox" bind:checked={allowPrivate}/><span>Allow this specific server on the plant private network</span></label><label>Read-only API token<input type="password" bind:value={token} required autocomplete="new-password"/></label><label>Allowed bucket IDs<input bind:value={buckets} placeholder="Comma-separated bucket IDs"/><small class="help">After connecting, inspect the available resources and update the permitted bucket IDs.</small></label>{:else if provider==='teams_workflow'}<label>Workflow webhook URL<input type="password" bind:value={url} required autocomplete="new-password"/></label>{:else}<label>Zoom account ID<input bind:value={accountId} required/></label><label>Client ID<input bind:value={clientId} required/></label><label>Client secret<input type="password" bind:value={clientSecret} required autocomplete="new-password"/></label><p class="help">Use an administrator-approved Zoom Server-to-Server OAuth app.</p>{/if}<div class="form-actions"><button type="button" class="button" onclick={()=>editing=null} disabled={busy}>Cancel</button><button class="button primary" disabled={busy}>{busy?'Saving…':'Save connection'}</button></div></form></section>{/if}
<div class="section-heading"><h2>Connected sources</h2><button class="text-button" onclick={load}><RefreshCw size={15}/>Refresh</button></div><div class="stack">{#each rows as connection}{@const Icon=icons[connection.provider]||Cable}<article class="card"><div class="row-card"><span class="feature-icon"><Icon size={23}/></span><div class="grow"><h3>{connection.name}</h3><p class="help">{connection.provider} · Last sync: {connection.last_synced_at?new Date(connection.last_synced_at).toLocaleString():'Not yet synchronized'}</p></div><span class="tag" class:green={connection.status==='connected'||connection.status==='active'}>{connection.status||'Configured'}</span><div class="row-actions">{#if canManage&&connection.status!=='disconnected'}<button class="button" onclick={()=>inspect(connection)} disabled={busy}>Resources</button>{/if}{#if connection.provider==='microsoft'}<button class="button" onclick={()=>sync(connection)} disabled={busy}><RefreshCw size={14}/>Sync</button>{/if}{#if canManage}<button class="icon-button" aria-label={`Disconnect ${connection.name}`} onclick={()=>disconnect(connection)} disabled={busy}><Trash2 size={16}/></button>{/if}</div></div>{#if connection.last_error||connection.error}<p class="form-error">{connection.last_error||connection.error}</p>{/if}{#if resources[connection.id]}<div class="connection-resources"><h3>Available resources</h3>{#if resources[connection.id].calendars}{#each resources[connection.id].calendars as calendar}<label class="check-row"><input type="checkbox" checked={(connection.config?.calendar_ids||[]).includes(calendar.id)} onchange={e=>chooseCalendar(connection,calendar.id,e.currentTarget.checked)}/><span>{calendar.name}<small>{calendar.id}</small></span></label>{/each}{:else if resources[connection.id].buckets}<label>Organization<select value={connection.config?.org_id||''} onchange={e=>updateResources(connection,{org_id:e.currentTarget.value,bucket_ids:[]})} disabled={!isAdmin}><option value="">Choose an organization</option>{#each resources[connection.id].organizations||[] as org}<option value={org.id}>{org.name}</option>{/each}</select></label><fieldset><legend>Allowed buckets</legend>{#each resources[connection.id].buckets.filter(b=>!connection.config?.org_id||b.org_id===connection.config.org_id) as bucket}<label class="check-row"><input type="checkbox" checked={(connection.config?.bucket_ids||[]).includes(bucket.id)} onchange={e=>updateResources(connection,{bucket_ids:e.currentTarget.checked?[...new Set([...(connection.config?.bucket_ids||[]),bucket.id])]:(connection.config?.bucket_ids||[]).filter(id=>id!==bucket.id)})} disabled={!isAdmin}/><span>{bucket.name}<small>{bucket.id}</small></span></label>{/each}</fieldset>{:else}<pre>{JSON.stringify(resources[connection.id],null,2)}</pre>{/if}</div>{/if}</article>{:else}<div class="empty card"><Cable size={28}/><h2>No connections in this space.</h2><p>Add the first source above, or start with uploaded documents and minutes.</p></div>{/each}</div>
{#if !workspaceId}<div class="section-heading"><h2>Next seven days</h2></div><div class="stack">{#each events as event}<article class="card row-card"><CalendarDays size={20}/><div class="grow"><h3>{event.title||event.subject}</h3><p class="help">{new Date(event.starts_at||event.start_at).toLocaleString()} · {event.organizer_name||event.organizer_email||''}</p></div><span class="tag">{event.status||'Scheduled'}</span></article>{:else}<p class="muted">Connect and synchronize a calendar to see upcoming meetings.</p>{/each}</div>{/if}
{#if capabilities}<section class="card capability-details"><h3>Connection readiness</h3><div class="readiness-grid">{#each [['Outlook calendar',capabilities.microsoft?.configured],['Voice transcription',capabilities.speech?.configured],['Email delivery',capabilities.email?.configured],['Credential encryption',capabilities.encrypted_connections]] as item}<div><span>{item[0]}</span><span class="tag" class:green={item[1]}>{item[1]?'Configured':'Needs setup'}</span></div>{/each}</div>{#if isAdmin&&capabilities.microsoft?.callback_url}<p class="help">Microsoft redirect URI: <code>{capabilities.microsoft.callback_url}</code></p>{/if}</section>{/if}

{#if canManage}<DeliveryPanel connections={rows} emailAvailable={!!capabilities?.email?.configured}/>{/if}
