<script>
 import { onMount } from 'svelte';import { Mail, Send, Undo2, RefreshCw } from 'lucide-svelte';import { api } from '../api.js';
 let { connections=[],emailAvailable=false }=$props();let channel=$state('email'),recipient=$state(''),connectionId=$state(''),subject=$state('Optimus connection test'),body=$state('Your notification channel is connected to Optimus.'),items=$state([]),busy=$state(false),error=$state(''),now=$state(Date.now());let timer,requestId=null,requestBody='';
 onMount(()=>{load();timer=setInterval(()=>now=Date.now(),1000);return()=>clearInterval(timer);});
 async function load(){try{items=await api('/deliveries');}catch(e){error=e.message;}}
 async function send(event){event.preventDefault();busy=true;error='';try{const payload={channel,recipient:channel==='email'?recipient:'',connection_id:channel==='email'?null:connectionId,subject,body,source_refs:[]};const snapshot=JSON.stringify(payload);if(!requestId||requestBody!==snapshot){requestId=crypto.randomUUID();requestBody=snapshot;}const item=await api('/deliveries',{method:'POST',body:{...payload,request_id:requestId}});requestId=null;items=[item,...items];}catch(e){error=e.message;}finally{busy=false;}}
 async function undo(item){busy=true;error='';try{await api(`/deliveries/${item.id}/undo`,{method:'POST',body:{}});await load();}catch(e){error=e.message;}finally{busy=false;}}
</script>
<section class="card delivery-panel"><div class="section-heading"><div><h2><Mail size={20}/>Notification delivery</h2><p class="help">Send a test or an approved message. Delivery waits at least 20 seconds so you can undo it.</p></div><button class="text-button" onclick={load}><RefreshCw size={15}/>Refresh</button></div>{#if error}<p class="form-error" role="alert">{error}</p>{/if}<form onsubmit={send}><div class="form-grid"><label>Channel<select bind:value={channel}><option value="email">Email</option><option value="slack">Slack</option><option value="teams">Microsoft Teams</option></select></label>{#if channel==='email'}<label>Recipient<input type="email" bind:value={recipient} required/></label>{:else}<label>Channel connection<select bind:value={connectionId} required><option value="">Choose a connection</option>{#each connections.filter(c=>c.provider===(channel==='slack'?'slack_webhook':'teams_workflow')&&c.status!=='disconnected') as connection}<option value={connection.id}>{connection.name}</option>{/each}</select></label>{/if}</div><label>Subject<input bind:value={subject} required/></label><label>Message<textarea rows="3" bind:value={body} required></textarea></label>{#if channel==='email'&&!emailAvailable}<p class="help">Email delivery needs administrator setup.</p>{/if}<div class="form-actions"><button class="button primary" disabled={busy||(channel==='email'&&!emailAvailable)}><Send size={15}/>Queue delivery</button></div></form><div class="compact-list">{#each items.slice(0,10) as item}<article><Mail size={16}/><div><strong>{item.subject}</strong><small>{({email:'Email',slack:'Slack',teams:'Teams'})[item.channel]||item.channel} · {item.recipient||'Channel'} · {item.status}</small>{#if item.last_error}<p class="form-error">{item.last_error}</p>{/if}</div>{#if item.status==='pending'}<button class="button compact" onclick={()=>undo(item)} disabled={busy}><Undo2 size={14}/>Cancel{new Date(item.undo_until).getTime()>now?` · ${Math.ceil((new Date(item.undo_until).getTime()-now)/1000)}s`:''}</button>{/if}</article>{/each}</div></section>
