<script>
 import { onMount } from 'svelte';import { Download, RefreshCw, Upload, Check } from 'lucide-svelte';import { api } from '../api.js';
 let { document, canWrite=false, saved=async()=>{} }=$props();let index=$state(null),revisions=$state([]),file=$state(null),busy=$state(false),error=$state('');
 onMount(load);
 async function load(){try{[index,revisions]=await Promise.all([api(`/documents/${document.id}/index`),api(`/documents/${document.id}/revisions`)]);}catch(e){error=e.message;}}
 async function retry(){busy=true;try{index=await api(`/documents/${document.id}/index/retry`,{method:'POST',body:{}});}catch(e){error=e.message;}finally{busy=false;}}
 async function upload(event){event.preventDefault();busy=true;try{const form=new FormData();form.append('file',file);await api(`/documents/${document.id}/revisions`,{method:'POST',body:form});document=await api(`/documents/${document.id}`);file=null;await load();await saved();}catch(e){error=e.message;}finally{busy=false;}}
</script>
{#if error}<div class="banner error" role="alert">{error}</div>{/if}{#if index}<div class="document-index"><div class="row-actions"><span class="tag">Revision {index.revision||'legacy'}</span><span class="tag">{index.index_status?.replaceAll('_',' ')}</span><small class="muted">{index.indexed_count??0} / {index.chunk_count??0} embedded chunks</small><button class="icon-button" aria-label="Refresh indexing status" onclick={load}><RefreshCw size={15}/></button></div>{#if index.error}<p class="form-error">{index.error}</p>{/if}<p class="help">{index.detail||'Document revisions preserve their source and chunk references. Lexical retrieval remains available while semantic indexing completes.'}</p><div class="row-actions">{#if index.original_available}<a class="button" href={`/api/documents/${document.id}/original`} download><Download size={15}/>Original file</a>{/if}{#if canWrite&&['failed','lexical_ready','pending'].includes(index.index_status)}<button class="button" disabled={busy} onclick={retry}>Retry indexing</button>{/if}</div></div>{/if}<div class="document-body">{document.body||'This document has no extracted text.'}</div>{#if canWrite}<form onsubmit={upload}><label>Replace with a new revision<input type="file" accept=".txt,.md,.csv,.json,.pdf,.docx" onchange={e=>file=e.currentTarget.files?.[0]||null}/></label><button class="button" disabled={busy||!file}><Upload size={15}/>{busy?'Uploading…':'Upload revision'}</button></form>{/if}{#if revisions.length>1}<details><summary>Version history · {revisions.length} revisions</summary>{#each revisions as revision}<p class="help">Revision {revision.revision} · {revision.index_status} · {new Date(revision.created_at).toLocaleString()}</p>{/each}</details>{/if}
