<script>
 import { onMount } from 'svelte';import { Video, Plus, ArrowLeft, FileText, Sparkles, Check, Users, Share2, CalendarDays, Trash2 } from 'lucide-svelte';import { api } from '../api.js';
 let { workspaces=[],user }=$props();
 let rows=$state([]),directory=$state([]),selected=$state(null),creating=$state(false),title=$state(''),startsAt=$state(''),attendees=$state([]),artifact=$state(''),artifactKind=$state('minutes'),sourceLabel=$state('Meeting owner'),review=$state({summary:'',decisions:[],actions:[],open_questions:[],workspace_ids:[]}),busy=$state(false),error=$state(''),notice=$state(''),consent=$state(false),connections=$state([]),providerConnection=$state(''),providerMeeting=$state(''),providerArtifacts=$state([]),sourceContent=$state({});
 let pollTimer,alive=true;onMount(()=>{load();return()=>{alive=false;clearTimeout(pollTimer);};});
 const extracting=$derived(selected?.extraction&&['queued','running'].includes(selected.extraction.status));
 async function load(){try{[rows,directory,connections]=await Promise.all([api('/meetings'),api('/meetings/people'),api('/connections')]);}catch(e){error=e.message;}}
 async function open(room){busy=true;error='';try{clearTimeout(pollTimer);selected=await api(`/meetings/${room.id}`);if(selected.extraction&&['queued','running'].includes(selected.extraction.status))pollExtraction(selected.id);setReview({...selected.minutes,workspace_ids:selected.workspace_ids||[]});}catch(e){error=e.message;}finally{busy=false;}}
 function setReview(r){review={summary:r.summary||'',decisions:(r.decisions||[]).map(d=>typeof d==='string'?{text:d,evidence:[]}:d),actions:(r.actions||[]).map(a=>({...a,assignee_id:a.assignee_id||'',due_at:a.due_at?new Date(new Date(a.due_at).getTime()-new Date(a.due_at).getTimezoneOffset()*60000).toISOString().slice(0,16):''})),open_questions:r.open_questions||[],workspace_ids:r.workspace_ids||[]};}
 async function create(e){e.preventDefault();busy=true;error='';try{selected=await api('/meetings',{method:'POST',body:{title,starts_at:startsAt?new Date(startsAt).toISOString():null,attendee_ids:attendees}});creating=false;title='';attendees=[];setReview({});await load();}catch(e){error=e.message;}finally{busy=false;}}
 async function saveArtifact(){busy=true;error='';try{await api(`/meetings/${selected.id}/artifacts`,{method:'POST',body:{kind:artifactKind,content:artifact,source_label:sourceLabel}});artifact='';notice='Source material saved.';await open(selected);}catch(e){error=e.message;}finally{busy=false;}}
 async function draft(){busy=true;error='';try{const result=await api(`/meetings/${selected.id}/draft`,{method:'POST',body:{external_ai_consent:consent}});selected=result;notice='Extraction queued. You can leave this page and return to follow progress.';pollExtraction(result.id);}catch(e){error=e.message;}finally{busy=false;}}
 const payload=()=>({...review,actions:review.actions.map(a=>({...a,assignee_id:a.assignee_id||null,due_at:a.due_at?new Date(a.due_at).toISOString():null}))});
 async function saveReview(publish=false){busy=true;error='';try{await api(`/meetings/${selected.id}/review`,{method:'PUT',body:payload()});if(publish)await api(`/meetings/${selected.id}/publish`,{method:'POST',body:{}});notice=publish?'Minutes published to the selected audience. Attendees can accept their personal updates.':'Reviewed draft saved.';await open(selected);await load();}catch(e){error=e.message;}finally{busy=false;}}
 async function accept(){busy=true;error='';try{await api(`/meetings/${selected.id}/accept`,{method:'POST',body:{}});notice='Meeting summary and assigned follow-ups added to your personal workspace.';}catch(e){error=e.message;}finally{busy=false;}}
 async function upload(e){const file=e.currentTarget.files?.[0];if(!file)return;artifact=await file.text();sourceLabel=file.name;}
 const canEdit=$derived(selected&&(selected.owner_id===user.id||selected.created_by===user.id));
  async function pollExtraction(id){clearTimeout(pollTimer);if(!alive||selected?.id!==id)return;try{const room=await api(`/meetings/${id}`);if(!alive||selected?.id!==id)return;selected=room;if(['queued','running'].includes(room.extraction?.status)){pollTimer=setTimeout(()=>pollExtraction(id),2200);}else{setReview({...room.minutes,workspace_ids:room.workspace_ids||[]});if(room.extraction?.error)error=room.extraction.error;else if(room.extraction?.status==='succeeded')notice='Draft ready. Review its evidence, decisions, and assignments.';await load();}}catch(e){if(alive){error=e.message;pollTimer=setTimeout(()=>pollExtraction(id),5000);}}}
  async function cancelExtraction(){try{await api(`/meetings/${selected.id}/extraction/cancel`,{method:'POST',body:{}});pollExtraction(selected.id);}catch(e){error=e.message;}}
  async function viewSource(item){try{const result=await api(`/meetings/${selected.id}/artifacts/${item.id}`);sourceContent={...sourceContent,[item.id]:result.content};}catch(e){error=e.message;}}
  async function discover(){busy=true;error='';try{const r=await api(`/connections/${providerConnection}/meeting-artifacts?meeting_id=${encodeURIComponent(providerMeeting)}`);providerArtifacts=r.artifacts;}catch(e){error=e.message;}finally{busy=false;}}
  async function importArtifact(item){busy=true;error='';try{await api(`/meetings/${selected.id}/provider-artifacts`,{method:'POST',body:{connection_id:providerConnection,meeting_id:providerMeeting,artifact_id:item.id}});notice='Provider transcript imported.';await open(selected);}catch(e){error=e.message;}finally{busy=false;}}
  async function archive(){busy=true;error='';try{await api(`/meetings/${selected.id}/archive`,{method:'POST',body:{}});await open(selected);await load();}catch(e){error=e.message;}finally{busy=false;}}
</script>
{#if error}<div class="banner error" role="alert">{error}</div>{/if}{#if notice}<div class="banner success" role="status"><Check size={16}/>{notice}</div>{/if}
{#if !selected}<section class="assistant-hero"><div><span class="eyebrow">FROM CONVERSATION TO FOLLOW-THROUGH</span><h2>A room for every decision.</h2><p>Bring the agenda, minutes, and agreed actions together. Share reviewed outcomes with the right workspaces.</p></div><button class="button primary" onclick={()=>creating=true}><Plus size={16}/>New Meeting Room</button></section>
{#if creating}<section class="card"><h2>Create Meeting Room</h2><form onsubmit={create}><div class="form-grid"><label>Meeting title<input bind:value={title} required/></label><label>Meeting time<input type="datetime-local" bind:value={startsAt}/></label></div><fieldset><legend>Attendees</legend><div class="people-picker">{#each directory as person}<label class="check-row"><input type="checkbox" value={person.id} bind:group={attendees}/><span>{person.name}<small>{person.email}</small></span></label>{/each}</div></fieldset><div class="form-actions"><button type="button" class="button" onclick={()=>creating=false}>Cancel</button><button class="button primary" disabled={busy||!title.trim()}>Create room</button></div></form></section>{/if}
<div class="card-grid">{#each rows as room}<article class="card meeting-card"><span class="feature-icon"><Video size={25}/></span><span class="tag float-tag">{room.status||'Open'}</span><h2>{room.title}</h2><p class="help">{room.starts_at?new Date(room.starts_at).toLocaleString():'Time not specified'}</p><button class="button" onclick={()=>open(room)} disabled={busy}>Open room<ArrowLeft size={15} style="transform:rotate(180deg)"/></button></article>{:else}<div class="empty card wide-grid"><Video size={30}/><h2>Turn meeting notes into shared understanding.</h2><p>Create a room and add an owner-supplied MoM or transcript to begin.</p></div>{/each}</div>
{:else}<div class="section-heading"><button class="text-button" onclick={()=>selected=null}><ArrowLeft size={16}/>All meeting rooms</button><span class="tag">{selected.status||'Open'}</span></div><section class="card"><div class="section-heading"><div><span class="eyebrow">MEETING ROOM</span><h2>{selected.title}</h2><p class="help">{selected.starts_at?new Date(selected.starts_at).toLocaleString():''}</p></div>{#if ['published','archived'].includes(selected.status)}<button class="button primary" onclick={accept} disabled={busy}><Check size={15}/>Add my updates</button>{/if}</div>{#if canEdit&&selected.status==='published'}<button class="text-button" onclick={archive} disabled={busy}>Archive this meeting room</button>{/if}<div class="attendee-chips">{#each selected.attendees||[] as attendee}<span class="tag">{attendee.name}{attendee.accepted_at?' · Accepted':''}</span>{/each}</div><p class="help">Approved minutes persist after the room is archived. Each attendee accepts personal follow-ups; publishing does not silently edit someone else’s notebook.</p></section>
{#if canEdit&&!['published','archived'].includes(selected.status)&&!extracting}<section class="card"><h2><FileText size={20}/>Meeting evidence</h2><p class="help">Upload or paste actual minutes or a transcript. Calendar agendas alone are not evidence of decisions.</p><div class="form-grid"><label>Artifact type<select bind:value={artifactKind}><option value="minutes">Owner-supplied minutes</option><option value="transcript">Transcript</option></select></label><label>Source label<input bind:value={sourceLabel}/></label></div><details class="native-artifacts"><summary>Import a native Zoom or Teams transcript</summary><label>Provider connection<select bind:value={providerConnection}><option value="">Choose a connection</option>{#each connections.filter(c=>['zoom','microsoft'].includes(c.provider)&&c.status!=='disconnected') as connection}<option value={connection.id}>{connection.name}</option>{/each}</select></label><label>Provider meeting ID<input bind:value={providerMeeting} placeholder="Zoom meeting UUID or Microsoft onlineMeeting ID"/></label><p class="help">Use the provider's meeting resource identifier, which may differ from the calendar event ID.</p><button class="button" onclick={discover} disabled={busy||!providerConnection||!providerMeeting}>Find transcript artifacts</button>{#each providerArtifacts as item}<div class="row-card"><span class="grow">{item.kind} · {item.created_at||item.id}</span><button class="button" onclick={()=>importArtifact(item)} disabled={busy}>Import</button></div>{:else}<p class="help">Available completed transcripts will appear here.</p>{/each}</details><label>Import text file<input type="file" accept=".txt,.md,.vtt,.srt" onchange={upload}/></label><label>Source content<textarea bind:value={artifact} rows="7" placeholder="Paste meeting minutes or transcript here…"></textarea></label><div class="form-actions"><button class="button" onclick={saveArtifact} disabled={busy||!artifact.trim()}>Save evidence</button></div>{#if selected.artifacts?.length}<details><summary>{selected.artifacts.length} saved artifacts</summary>{#each selected.artifacts as item}<div><p class="help">{item.source_label||item.kind} · {item.created_at?new Date(item.created_at).toLocaleString():''}</p><button class="text-button" onclick={()=>viewSource(item)}>View source text</button>{#if sourceContent[item.id]}<div class="document-body">{sourceContent[item.id]}</div>{/if}</div>{/each}</details>{/if}<label class="check-row"><input type="checkbox" bind:checked={consent}/><span>Send this room’s evidence to the configured AI model for extraction.</span></label><button class="button primary" onclick={draft} disabled={busy||!consent}><Sparkles size={15}/>{busy?'Working…':'Extract draft minutes'}</button></section>{/if}
{#if selected.extraction}<div class="agent-progress" role="status"><div class="row-actions"><strong>Transcript extraction · {selected.extraction.status}</strong><span>{selected.extraction.completed_chunks||0} / {selected.extraction.total_chunks||0} sections</span>{#if extracting}<button class="button compact" onclick={cancelExtraction}>Cancel extraction</button>{/if}</div>{#if selected.extraction.error}<p class="form-error">{selected.extraction.error}</p>{/if}</div>{/if}<section class="card minutes-editor"><div class="section-heading"><h2>Review outcomes</h2><span class="tag"><Users size={13}/>Attendee review</span></div><label>Summary<textarea bind:value={review.summary} rows="5" disabled={busy||!canEdit||extracting||['published','archived'].includes(selected.status)}></textarea></label><div class="section-heading"><h3>Decisions</h3>{#if canEdit&&!extracting&&!['published','archived'].includes(selected.status)}<button class="text-button" onclick={()=>review.decisions=[...review.decisions,{text:'',evidence:[]}]}><Plus size={15}/>Add decision</button>{/if}</div>{#each review.decisions as decision,i}<div class="review-item"><label>Decision {i+1}<textarea rows="2" bind:value={decision.text} disabled={busy||!canEdit||extracting||['published','archived'].includes(selected.status)}></textarea></label>{#each decision.evidence||[] as evidence}<p class="help"><strong>Evidence:</strong> {evidence.quote}</p>{/each}{#if canEdit&&!extracting&&!['published','archived'].includes(selected.status)}<button class="text-button" onclick={()=>review.decisions=review.decisions.filter((_,n)=>n!==i)}><Trash2 size={14}/>Remove</button>{/if}</div>{:else}<p class="muted">No decisions recorded.</p>{/each}
<div class="section-heading"><h3>Action items</h3>{#if canEdit&&!extracting&&!['published','archived'].includes(selected.status)}<button class="text-button" onclick={()=>review.actions=[...review.actions,{text:'',evidence:[],assignee_id:'',due_at:''}]}><Plus size={15}/>Add action</button>{/if}</div>{#each review.actions as action,i}<div class="review-item"><label>Action {i+1}<textarea rows="2" bind:value={action.text} disabled={busy||!canEdit||extracting||['published','archived'].includes(selected.status)}></textarea></label><div class="form-grid"><label>Owner<select bind:value={action.assignee_id} disabled={busy||!canEdit||extracting||['published','archived'].includes(selected.status)}><option value="">Unresolved — do not infer</option>{#each selected.attendees||[] as person}<option value={person.user_id}>{person.name}</option>{/each}</select></label><label>Due date<input type="datetime-local" bind:value={action.due_at} disabled={busy||!canEdit||extracting||['published','archived'].includes(selected.status)}/></label></div>{#each action.evidence||[] as evidence}<p class="help"><strong>Evidence:</strong> {evidence.quote}</p>{/each}{#if canEdit&&!extracting&&!['published','archived'].includes(selected.status)}<button class="text-button" onclick={()=>review.actions=review.actions.filter((_,n)=>n!==i)}><Trash2 size={14}/>Remove</button>{/if}</div>{:else}<p class="muted">No action items recorded.</p>{/each}
<label>Open questions<textarea rows="3" value={review.open_questions.join('\n')} oninput={e=>review.open_questions=e.currentTarget.value.split('\n').filter(Boolean)} disabled={busy||!canEdit||extracting||['published','archived'].includes(selected.status)}></textarea></label>{#if canEdit&&!extracting&&!['published','archived'].includes(selected.status)}<fieldset><legend>Publish reviewed minutes to</legend>{#each workspaces.filter(w=>w.membership_role==='manager') as w}<label class="check-row"><input type="checkbox" value={w.id} bind:group={review.workspace_ids}/><span>{w.name}</span></label>{:else}<p class="muted">No managed workspaces. Minutes can still be shared with attendees.</p>{/each}</fieldset><div class="form-actions"><button class="button" onclick={()=>saveReview(false)} disabled={busy}>Save reviewed draft</button><button class="button primary" onclick={()=>saveReview(true)} disabled={busy||!review.summary.trim()}><Share2 size={15}/>Approve and publish</button></div>{/if}</section>{/if}
