<script>
  import { onMount } from 'svelte';
  import { Mic, Square, Sparkles, ArrowRight, Clock, Check, Undo2, Folder, RefreshCw, CalendarCheck } from 'lucide-svelte';
  import { api } from '../api.js';
  let { projects = [], onSaved = async()=>{} } = $props();
  let text=$state(''), projectId=$state(''), busy=$state(false), error=$state(''), result=$state(null), captures=$state([]), tasks=$state([]), recording=$state(false), elapsed=$state(0), consent=$state(true), checkin=$state(null), due=$state(''), now=$state(Date.now());
  let recorder, stream, timer, clock, chunks=[],alive=true,requestId=null,requestText='';
  const fmt=v=>v?new Date(v).toLocaleString():'';
  onMount(()=>{load();clock=setInterval(()=>now=Date.now(),1000);return()=>{alive=false;clearInterval(timer);clearInterval(clock);if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());};});
  async function load(){try{[captures,tasks]=await Promise.all([api('/personal/captures'),api('/personal/tasks')]);}catch(e){error=e.message;}}
  async function record(){error='';if(recording){recorder.stop();return;}if(!consent){error='Enable external AI consent before recording for transcription.';return;}try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('Voice recording needs a supported browser and HTTPS. You can type your thought below.');stream=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive){stream.getTracks().forEach(t=>t.stop());return;}chunks=[];const mime=['audio/webm;codecs=opus','audio/mp4','audio/webm'].find(m=>MediaRecorder.isTypeSupported(m));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:{});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=async()=>{clearInterval(timer);recording=false;stream.getTracks().forEach(t=>t.stop());if(!alive)return;busy=true;try{const form=new FormData();const ext=recorder.mimeType.includes('mp4')?'m4a':'webm';form.append('external_ai_consent','true');form.append('file',new Blob(chunks,{type:recorder.mimeType}),`capture.${ext}`);const r=await api('/speech/transcribe',{method:'POST',body:form});text=[text,r.text].filter(Boolean).join('\n');}catch(e){error=e.message;}finally{busy=false;}};recorder.start();recording=true;elapsed=0;timer=setInterval(()=>{elapsed++;if(elapsed>=300&&recorder.state==='recording')recorder.stop();},1000);}catch(e){error=e.message;}}
  async function save(event){event.preventDefault();if(!text.trim()||busy)return;busy=true;error='';try{if(!requestId||requestText!==text){requestId=crypto.randomUUID();requestText=text;}const body={text,request_id:requestId,project_id:projectId||null,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,classify:consent,external_ai_consent:consent};result=checkin?await api(`/personal/checkins/${checkin.id}/complete`,{method:'POST',body:{text:body.text,request_id:body.request_id,classify:body.classify,external_ai_consent:body.external_ai_consent}}):await api('/personal/captures',{method:'POST',body});requestId=null;requestText='';text='';checkin=null;if(result.suggested_due_at){const d=new Date(result.suggested_due_at);due=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}await load();await onSaved();}catch(e){error=e.message;}finally{busy=false;}}
  async function apply(memory=false){busy=true;error='';try{result=await api(`/personal/captures/${result.capture.id}/apply`,{method:'POST',body:{due_at:!memory&&due?new Date(due).toISOString():null,project_id:projectId||null,create_memory:memory}});await load();await onSaved();}catch(e){error=e.message;}finally{busy=false;}}
  async function undo(action){busy=true;try{await api(`/personal/actions/${action.id}/undo`,{method:'POST',body:{}});result={...result,actions:result.actions.map(a=>a.id===action.id?{...a,status:'undone'}:a)};await load();await onSaved();}catch(e){error=e.message;}finally{busy=false;}}
  async function startCheckin(){try{checkin=await api('/personal/checkins',{method:'POST',body:{}});}catch(e){error=e.message;}}
  function reviewCapture(item){result=item;if(item.suggested_due_at){const d=new Date(item.suggested_due_at);due=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}else due='';}
</script>
<section class="assistant-hero"><div><span class="eyebrow">YOUR EVERYDAY ASSISTANT</span><h2>Capture the thought.<br/>Keep the next step in sight.</h2><p>Tell Optimus what happened, what you noticed, or what you want to follow up.</p></div><span class="assistant-orb"><Sparkles size={37}/></span></section>
{#if error}<div class="banner error" role="alert">{error}</div>{/if}
<div class="assistant-grid"><section class="card capture-card"><div class="section-heading"><h2>{checkin?'Your daily check-in':'What’s on your mind?'}</h2><button class="text-button" onclick={startCheckin} disabled={busy||recording}><CalendarCheck size={16}/>Daily check-in</button></div>{#if checkin}<div class="checkin-prompts">{#each checkin.prompts||[] as prompt}<p>{typeof prompt==='string'?prompt:prompt.text}</p>{/each}</div>{/if}<form onsubmit={save}><label class="sr-only" for="capture-thought">Your thought</label><textarea id="capture-thought" bind:value={text} rows="6" placeholder="The cooling water reading looked unusual at 10:30. I want to look into it tomorrow…" disabled={busy}></textarea><div class="capture-controls"><button type="button" class="button" class:recording onclick={record} disabled={busy}>{#if recording}<Square size={16}/>Stop · {elapsed}s{:else}<Mic size={16}/>Speak{/if}</button><label class="inline-label"><Folder size={15}/><select bind:value={projectId} disabled={busy}><option value="">Let Optimus suggest a project</option>{#each projects.filter(p=>!p.archived) as p}<option value={p.id}>{p.name}</option>{/each}</select></label><button class="button primary" disabled={busy||recording||!text.trim()}>{busy?'Working…':'Capture'}<ArrowRight size={16}/></button></div><label class="check-row"><input type="checkbox" bind:checked={consent}/><span>Use AI to classify this entry and suggest the next step. Voice transcription uses the configured speech provider.</span></label></form>
{#if result}<div class="capture-result" aria-live="polite"><div class="row-actions"><Check size={17}/><strong>Saved to your notebook</strong><span class="tag">{result.capture?.classification?.labels?.join(' · ')||result.note?.kind||'Note'}</span></div>{#if result.capture?.classification_error}<p class="help">{result.capture.classification_error} Your original note was retained.</p>{/if}{#if result.warning}<p class="help">{result.warning}</p>{/if}{#if result.suggested_due_at&&result.task?.status==='proposed'}<p class="help">A follow-up was suggested. Review its time before setting the reminder.</p><div class="form-grid"><label>Remind me at<input type="datetime-local" bind:value={due}/></label><button class="button" onclick={()=>apply(false)} disabled={busy||!due}><Clock size={15}/>Set reminder</button></div>{/if}{#if result.capture?.classification?.memory_text&&!result.actions?.some(a=>a.kind==='create_memory'&&a.status==='applied')}<div class="capture-memory"><p class="help">Suggested remembered context: {result.capture.classification.memory_text}</p><button class="button compact" onclick={()=>apply(true)} disabled={busy}>Remember this context</button></div>{/if}{#each result.actions||[] as action}{#if action.status==='undone'}<p class="help">Action undone.</p>{:else if action.undo_until&&new Date(action.undo_until).getTime()>now}<button class="button compact" onclick={()=>undo(action)} disabled={busy}><Undo2 size={14}/>Undo {action.kind?.replaceAll('_',' ')} · {Math.min(20,Math.ceil((new Date(action.undo_until).getTime()-now)/1000))}s</button>{/if}{/each}<p class="help">Review automatic changes anytime in Activity.</p></div>{/if}</section>
<aside class="stack"><section class="card"><span class="eyebrow">FOLLOW THROUGH</span><h2>Open commitments</h2><div class="compact-list">{#each tasks.filter(t=>!['done','dismissed'].includes(t.status)).slice(0,6) as task}<article><Clock size={16}/><div><strong>{task.title||task.text}</strong><small>{task.suggested_due_at?fmt(task.suggested_due_at):'No reminder time yet'}</small></div><span class="tag">{task.status}</span><button class="icon-button" aria-label={`Complete ${task.title}`} disabled={busy} onclick={async()=>{try{await api(`/personal/tasks/${task.id}`,{method:'PATCH',body:{status:'done'}});await load();}catch(e){error=e.message;}}}><Check size={15}/></button></article>{:else}<p class="muted">Commitments captured from your notes will appear here.</p>{/each}</div></section><section class="card"><h3>A place for unpolished thoughts</h3><p class="help">Your original words are saved first. Labels and filing suggestions help you find them later. A reminder keeps the original observation date even when it is due another day.</p></section></aside></div>
<div class="section-heading"><h2>Recently captured</h2><button class="text-button" onclick={load}><RefreshCw size={15}/>Refresh</button></div><div class="notes-grid">{#each captures.slice(0,9) as item}{@const capture=item.capture}<article class="note-card"><header><span class="tag">{capture.classification?.labels?.join(' · ')||item.note?.kind||'Note'}</span><time>{fmt(capture.created_at)}</time></header><p class="note-body">{capture.original_text||capture.text||item.note?.body}</p>{#if capture.data_date}<small class="help">Observation date: {String(capture.data_date)}</small>{/if}{#if item.task?.status==='proposed'||capture.classification?.memory_text}<footer><button class="text-button" onclick={()=>reviewCapture(item)}>Review next steps<ArrowRight size={14}/></button></footer>{/if}</article>{:else}<div class="empty card wide-grid"><Sparkles size={28}/><h2>Start with one thought.</h2><p>Type or speak above. You can organize it later.</p></div>{/each}</div>
