<script>
 import { onMount } from 'svelte';import { Folder, Plus, ArrowLeft, FileText } from 'lucide-svelte';import { api,query } from '../api.js';
 let { project,close }=$props();let folders=$state([]),placements=$state([]),notes=$state([]),parent=$state(null),selected=$state(null),name=$state(''),busy=$state(false),error=$state('');
 onMount(load);
 async function load(){try{[folders,placements,notes]=await Promise.all([api('/personal/folders'+query({project_id:project.id})),api('/personal/placements'),api('/notes'+query({project_id:project.id}))]);}catch(e){error=e.message;}}
 async function create(e){e.preventDefault();busy=true;error='';try{await api('/personal/folders',{method:'POST',body:{project_id:project.id,parent_id:parent,name}});name='';await load();}catch(e){error=e.message;}finally{busy=false;}}
 const shown=$derived(selected?notes.filter(n=>placements.some(p=>p.note_id===n.id&&p.folder_id===selected.id)):notes.filter(n=>!placements.some(p=>p.note_id===n.id)));
 function open(folder){selected=folder;parent=folder.id;}
 function back(){const current=folders.find(f=>f.id===parent);parent=current?.parent_id||null;selected=folders.find(f=>f.id===parent)||null;}
</script>
<section class="card project-folders"><div class="section-heading"><div><span class="eyebrow">PROJECT FOLDERS</span><h2>{project.name}{selected?` / ${selected.name}`:''}</h2></div><button class="text-button" onclick={close}>Close folders</button></div>{#if error}<p class="form-error" role="alert">{error}</p>{/if}{#if parent}<button class="text-button" onclick={back}><ArrowLeft size={15}/>Parent folder</button>{/if}<div class="folder-grid">{#each folders.filter(f=>(f.parent_id||null)===parent) as folder}<button onclick={()=>open(folder)}><Folder size={19}/><strong>{folder.name}</strong><small>{placements.filter(p=>p.folder_id===folder.id).length} notes</small></button>{:else}<p class="help">No subfolders here yet.</p>{/each}</div><form onsubmit={create} class="folder-form"><label class="sr-only" for="folder-name">New folder name</label><input id="folder-name" bind:value={name} placeholder="New folder name" required maxlength="120"/><button class="button" disabled={busy||!name.trim()}><Plus size={15}/>Create folder</button></form><div class="section-heading"><h3>{selected?'Notes in this folder':'Unfiled project notes'}</h3></div><div class="compact-list">{#each shown as note}<article><FileText size={17}/><div><strong>{note.title}</strong><p class="help pre-wrap">{note.body}</p></div></article>{:else}<p class="help">No notes here. Weekly organization files captured notes by their reviewed labels.</p>{/each}</div></section>
