<script>
 import { BookOpen, Activity, Clock, AlertTriangle } from 'lucide-svelte';
 let { report }=$props();
 const number=value=>typeof value==='number'&&Number.isFinite(value)?new Intl.NumberFormat(undefined,{maximumFractionDigits:3}).format(value):'Unavailable';
 const fmt=value=>value?new Date(value).toLocaleString(undefined,{timeZoneName:'short'}):'—';
 const label=value=>String(value||'').replaceAll('_',' ');
 const data=$derived(report.result_data||{});
 function maximum(metric){return Math.max(...Object.values(metric.windows||{}).map(w=>Math.abs(metric.aggregation==='mean'?w.mean||0:w.rate_per_hour||0)),0.00001);}
</script>
<article class="card report-card"><header><span class="feature-icon"><BookOpen size={23}/></span><div class="grow"><h2>{report.title}</h2><small class="muted">{fmt(report.created_at)}</small></div>{#if data.outcome}<span class="tag" class:green={data.outcome==='pass'} class:danger={['fail','unavailable'].includes(data.outcome)}>{data.outcome}</span>{/if}</header>
{#if data.metrics?.length}<div class="report-metrics">{#each data.metrics as metric}<section class="metric-report"><div class="section-heading"><h3>{metric.label} <small class="muted">{metric.unit}</small></h3><span class="tag">{metric.aggregation}</span></div>{#if Object.keys(metric.windows||{}).length===1}{@const value=Object.values(metric.windows)[0]}<div class="metric-cards"><div><span>Calculated value</span><strong>{number(value.value)}</strong><small>{metric.unit} · {value.outcome}</small></div><div><span>Data coverage</span><strong>{value.coverage_ratio!=null?`${number(value.coverage_ratio*100)}%`:'Not configured'}</strong><small>{value.count??0} observations</small></div><div><span>Latest sample age</span><strong>{number(value.latest_age_minutes)}</strong><small>minutes at reporting end</small></div><div><span>Deviation score</span><strong>{number(value.anomaly_propensity_score)}</strong><small>0–100 · heuristic indicator</small></div></div><p class="help">{fmt(value.window?.start)} → {fmt(value.window?.end)}</p>{#if value.reasons?.length}<ul class="report-reasons">{#each value.reasons as reason}<li>{reason}</li>{/each}</ul>{/if}{:else}<div class="comparison-bars" aria-label={`${metric.label} comparison`}>{#each Object.entries(metric.windows) as [key,value]}{@const amount=['fail','unavailable'].includes(value.outcome)?null:(metric.aggregation==='mean'?value.mean:value.rate_per_hour)}<div><span>{label(key)}</span><div class="comparison-track"><div style={`width:${amount!=null?Math.min(100,Math.abs(amount)/maximum(metric)*100):0}%`}></div></div><strong>{number(amount)}</strong><small>{metric.unit}{metric.aggregation==='mean'?'':'/h'}</small></div>{/each}</div><p class="help">{metric.aggregation==='mean'?'Mean readings are compared; long windows use populated hourly means.':'Rates are normalized by the measured reporting duration. Totals from unequal windows are not directly compared.'}</p><div class="table-wrap"><table><thead><tr><th>Reporting window</th><th>Dates</th><th>Validation</th><th>Current week vs this period</th></tr></thead><tbody>{#each Object.entries(metric.windows) as [key,value]}{@const comparison=metric.comparisons?.[key]}<tr><td>{label(key)}</td><td>{fmt(value.window?.start)}<br/>{fmt(value.window?.end)}</td><td><span class="tag" class:danger={['fail','unavailable'].includes(value.outcome)}>{value.outcome}</span>{#each value.reasons||[] as reason}<small class="help">{reason}</small>{/each}</td><td>{#if comparison}{comparison.percent_change!=null?`${comparison.percent_change>0?'+':''}${number(comparison.percent_change)}%`:'Withheld'}{#if comparison.reason}<small class="help">{comparison.reason}</small>{/if}{:else}Current period{/if}</td></tr>{/each}</tbody></table></div>{/if}</section>{/each}</div><p class="report-disclaimer"><Activity size={14}/>Deviation scores measure unusual values within this data window. They are not calibrated probabilities of an incident.</p>{/if}
{#if data.metrics?.length}<details><summary>Full report and evidence</summary><div class="report-body">{report.body}</div></details>{:else}<div class="report-body">{report.body}</div>{/if}{#if report.source_refs?.length}<details><summary>Source references</summary>{#each report.source_refs as source}<p class="source-ref">{source.title||source.id}{source.field?` · ${source.field}`:''}{source.window_start?` · ${fmt(source.window_start)} to ${fmt(source.window_end)}`:''}</p>{/each}</details>{/if}
</article>
