<script>
 import { onMount } from 'svelte'; import { FileText, Sparkles, Check, History } from 'lucide-svelte'; import { api } from '../api.js';
 let { workspace, canManage=false, onSaved=async()=>{} }=$props();
 let brief=$state(null),body=$state(''),details=$state({responsibilities:'',terminology:'',units:'SI',expected_outputs:''}),busy=$state(false),error=$state(''),notice=$state(''),consent=$state(false);
 onMount(load);
 async function load(){try{brief=await api(`/workspaces/${workspace.id}/brief`);const current=brief.drafts?.[0]||brief.published;body=current?.body||brief.fallback_purpose||workspace.description||'';details={...details,...current?.details};}catch(e){error=e.message;}}
 async function save(publish=false){busy=true;error='';try{const draft=await api(`/workspaces/${workspace.id}/brief`,{method:'POST',body:{body,details}});if(publish)await api(`/workspaces/${workspace.id}/brief/${draft.id}/publish`,{method:'POST',body:{}});notice=publish?'Brief published. New assistant runs will use this revision.':'Draft saved.';await load();await onSaved();}catch(e){error=e.message;}finally{busy=false;}}
 async function generate(){busy=true;error='';try{const draft=await api(`/workspaces/${workspace.id}/brief/generate`,{method:'POST',body:{instructions:body,external_ai_consent:consent}});body=draft.body;details={...details,...draft.details};notice='AI draft ready. Review it before publishing.';brief=await api(`/workspaces/${workspace.id}/brief`);}catch(e){error=e.message;}finally{busy=false;}}
</script>
{#if error}<div class="banner error" role="alert">{error}</div>{/if}{#if notice}<div class="banner success" role="status"><Check size={16}/>{notice}</div>{/if}
<section class="card brief-editor"><div class="section-heading"><div><span class="eyebrow">ALWAYS-LOADED WORKSPACE CONTEXT</span><h2><FileText size={20}/>Workspace brief</h2></div><span class="tag">{brief?.published?`Published revision ${brief.published.revision||brief.published.version||'1'}`:'Purpose fallback'}</span></div><p class="help">Explain what this workspace does, how its data should be interpreted, and what a useful answer looks like. Published instructions are included in every run. They cannot grant access or enable a tool.</p><label>Assistant instructions<textarea rows="10" bind:value={body} disabled={!canManage||busy} placeholder="This workspace supports… Prefer approved SOPs. State units, dates, and evidence. Separate observations from hypotheses."></textarea></label><div class="form-grid"><label>Responsibilities<textarea rows="3" bind:value={details.responsibilities} disabled={!canManage||busy}></textarea></label><label>Terminology and assets<textarea rows="3" bind:value={details.terminology} disabled={!canManage||busy}></textarea></label><label>Units<input bind:value={details.units} disabled={!canManage||busy}/></label><label>Expected outputs<input bind:value={details.expected_outputs} placeholder="Shift handover, validation report, incident review" disabled={!canManage||busy}/></label></div>{#if canManage}<label class="check-row"><input type="checkbox" bind:checked={consent}/><span>Allow AI to draft this brief using the workspace purpose and authorized documents.</span></label><div class="form-actions"><button class="button" onclick={generate} disabled={busy||!consent}><Sparkles size={16}/>Draft with AI</button><button class="button" onclick={()=>save(false)} disabled={busy||!body.trim()}>Save draft</button><button class="button primary" onclick={()=>save(true)} disabled={busy||!body.trim()}>Publish brief</button></div>{/if}</section>
{#if brief?.drafts?.length}<section class="card"><h3><History size={17}/>Recent drafts</h3><div class="compact-list">{#each brief.drafts as draft}<article><div class="grow"><strong>Revision {draft.revision||draft.version||draft.id.slice(0,8)}</strong><small>{new Date(draft.created_at).toLocaleString()}</small></div><button class="button compact" disabled={!canManage} onclick={()=>{body=draft.body;details={...details,...draft.details};}}>Load draft</button></article>{/each}</div></section>{/if}
