<script>
 import { ArrowRight, Check, Layers, FileText, Cable, Users } from 'lucide-svelte'; import { api } from '../api.js';
 let { scopes=[],close,saved }=$props();
 let step=$state(0),name=$state(''),scopeId=$state(''),description=$state(''),brief=$state(''),classification=$state(1),external=$state(true),busy=$state(false),error=$state(''),created=$state(null);
 const steps=[{label:'Identity',icon:Layers},{label:'Assistant brief',icon:FileText},{label:'Review',icon:Check}];
 async function create(){busy=true;error='';try{if(!created)created=await api('/workspaces',{method:'POST',body:{name,scope_id:scopeId,description,classification:Number(classification),external_ai_enabled:external}});const draft=await api(`/workspaces/${created.id}/brief`,{method:'POST',body:{body:brief||description,details:{}}});await api(`/workspaces/${created.id}/brief/${draft.id}/publish`,{method:'POST',body:{}});await saved(created);}catch(e){error=e.message;}finally{busy=false;}}
</script>
<div class="wizard-steps">{#each steps as item,i}<div class:active={i===step} class:done={i<step}><span>{i<step?'✓':i+1}</span>{item.label}</div>{/each}</div>
{#if error}<div class="banner error" role="alert">{error}{#if created}<p>The workspace is already created. Retry to finish its brief.</p>{/if}</div>{/if}
{#if step===0}<label>Workspace name<input bind:value={name} placeholder="Utilities maintenance" required/></label><label>Organizational scope<select bind:value={scopeId} required><option value="">Choose a unit or team</option>{#each scopes as scope}<option value={scope.id}>{scope.name} · {scope.kind}</option>{/each}</select></label><label>Purpose<textarea bind:value={description} rows="3" placeholder="What this team is responsible for…"></textarea></label><label>Classification<select bind:value={classification}><option value={1}>Internal</option><option value={2}>Confidential</option><option value={3}>Restricted</option></select></label><label class="check-row"><input type="checkbox" bind:checked={external}/><span>Enable external AI for this workspace</span></label>
{:else if step===1}<h3>Give Optimus the team’s context</h3><p class="help">This is the instruction prefix for every workspace conversation and agent. Add responsibilities, terminology, preferred units, and expected outputs.</p><label>Workspace brief<textarea bind:value={brief} rows="10" placeholder="This workspace supports… When investigating an issue, present evidence, likely causes, recommended checks, and open questions. Use SI units and prefer current approved SOPs."></textarea></label><p class="help">After connecting sources and uploading documents, you can ask AI to expand this into a reviewed draft.</p>
{:else}<div class="review-list"><h2>{name}</h2><p>{scopes.find(s=>s.id===scopeId)?.name}</p><p class="pre-wrap">{description}</p><div class="document-body">{brief||description}</div><p class="help">You become a workspace manager. Next, invite your colleagues and add sources from the workspace tabs.</p><div class="row-actions"><span class="tag"><Users size={14}/>Explicit membership</span><span class="tag"><Cable size={14}/>Connections added next</span></div></div>{/if}
<div class="form-actions"><button class="button" onclick={step===0?close:()=>step--} disabled={busy}>{step===0?'Cancel':'Back'}</button>{#if step<2}<button class="button primary" disabled={step===0?(!name.trim()||!scopeId||!description.trim()):!brief.trim()} onclick={()=>{if(step===0&&!brief)brief=description;step++;}}>Continue<ArrowRight size={15}/></button>{:else}<button class="button primary" onclick={create} disabled={busy}>{busy?'Creating…':'Create workspace'}</button>{/if}</div>
