"""Durable agents, hybrid knowledge, personal assistant and enterprise governance.

Immutable SQLAlchemy schema snapshot. Requires PostgreSQL16+ with pgvector.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy
revision = '0002_agent_platform'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_service', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('scheduled_jobs', sa.Column('execution_user_id', sa.Uuid(as_uuid=False), nullable=True))
    op.create_foreign_key('fk_scheduled_jobs_execution_user_id_users','scheduled_jobs','users',['execution_user_id'],['id'],ondelete='RESTRICT')
    op.add_column('scheduled_jobs', sa.Column('task_type', sa.String(length=40), server_default=sa.text("'analysis'"), nullable=False))
    op.add_column('scheduled_jobs', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('scheduled_jobs', sa.Column('timezone', sa.String(length=80), server_default=sa.text("'UTC'"), nullable=False))
    op.add_column('scheduled_jobs', sa.Column('approval_status', sa.String(length=20), server_default=sa.text("'legacy'"), nullable=False))
    op.add_column('scheduled_jobs', sa.Column('revision', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('scheduled_jobs', sa.Column('approved_revision', sa.Integer(), nullable=True))
    op.add_column('scheduled_jobs', sa.Column('activation_not_before', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scheduled_jobs', sa.Column('dependency_policy', sa.String(length=20), server_default=sa.text("'pass_warn'"), nullable=False))
    op.add_column('job_runs', sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('reports', sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.create_table('assistant_settings',
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('reminder_mode', sa.String(length=20), server_default=sa.text("'suggest'"), nullable=False),
    sa.Column('memory_mode', sa.String(length=20), server_default=sa.text("'suggest'"), nullable=False),
    sa.Column('organization_mode', sa.String(length=20), server_default=sa.text("'suggest'"), nullable=False),
    sa.Column('daily_checkin_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('daily_checkin_time', sa.String(length=5), server_default=sa.text("'17:00'"), nullable=False),
    sa.Column('reminder_hour', sa.Integer(), server_default=sa.text('13'), nullable=False),
    sa.Column('next_checkin_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_organization_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("memory_mode IN ('off','suggest','automatic')", name=op.f('ck_assistant_settings_memory_mode')),
    sa.CheckConstraint("organization_mode IN ('off','suggest','automatic')", name=op.f('ck_assistant_settings_organization_mode')),
    sa.CheckConstraint("reminder_mode IN ('off','suggest','automatic')", name=op.f('ck_assistant_settings_reminder_mode')),
    sa.CheckConstraint('reminder_hour BETWEEN 0 AND 23', name=op.f('ck_assistant_settings_reminder_hour')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_assistant_settings_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id', name=op.f('pk_assistant_settings'))
    )
    op.create_index('ix_assistant_settings_organization_due', 'assistant_settings', ['next_organization_at'], unique=False)
    op.create_index('ix_assistant_settings_daily_due', 'assistant_settings', ['next_checkin_at'], unique=False)
    op.create_table('meeting_rooms',
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('minutes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('workspace_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open','draft','reviewed','published','archived')", name=op.f('ck_meeting_rooms_status')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_meeting_rooms_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_rooms'))
    )
    op.create_index(op.f('ix_meeting_rooms_owner_id'), 'meeting_rooms', ['owner_id'], unique=False)
    op.create_table('personal_actions',
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('request_id', sa.String(length=180), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'applied'"), nullable=False),
    sa.Column('resource_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('undo_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','applied','undone','cancelled','failed')", name=op.f('ck_personal_actions_status')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_personal_actions_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_actions')),
    sa.UniqueConstraint('owner_id', 'request_id', name='uq_personal_actions_owner_request')
    )
    op.create_index('ix_personal_actions_due', 'personal_actions', ['status', 'undo_until'], unique=False)
    op.create_index('ix_personal_actions_owner_created', 'personal_actions', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_personal_actions_owner_id'), 'personal_actions', ['owner_id'], unique=False)
    op.create_table('scope_role_assignments',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('scope_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('manage_workspaces', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('manage_people', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_scope_role_assignments_assigned_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], name=op.f('fk_scope_role_assignments_scope_id_scopes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scope_role_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scope_role_assignments')),
    sa.UniqueConstraint('user_id', 'scope_id', name='uq_scope_role_assignments_user_scope')
    )
    op.create_index(op.f('ix_scope_role_assignments_user_id'), 'scope_role_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_scope_role_assignments_scope_id'), 'scope_role_assignments', ['scope_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('language', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('units', sa.String(length=40), nullable=False),
    sa.Column('response_style', sa.String(length=80), nullable=False),
    sa.Column('personal_instructions', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences')),
    sa.UniqueConstraint('user_id', name='uq_user_preferences_user')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_table('connections',
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('workspace_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('microsoft','zoom','influxdb','teams_workflow')", name=op.f('ck_connections_provider')),
    sa.CheckConstraint("status IN ('pending','connected','error','disconnected')", name=op.f('ck_connections_status')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_connections_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_connections_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connections'))
    )
    op.create_index(op.f('ix_connections_owner_id'), 'connections', ['owner_id'], unique=False)
    op.create_index('ix_connections_sync', 'connections', ['provider', 'status', 'next_sync_at'], unique=False)
    op.create_index(op.f('ix_connections_workspace_id'), 'connections', ['workspace_id'], unique=False)
    op.create_table('meeting_artifacts',
    sa.Column('room_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_label', sa.String(length=300), nullable=False),
    sa.Column('provider_reference', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('imported_by', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('transcript','minutes','notes')", name=op.f('ck_meeting_artifacts_kind')),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], name=op.f('fk_meeting_artifacts_imported_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_id'], ['meeting_rooms.id'], name=op.f('fk_meeting_artifacts_room_id_meeting_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_artifacts')),
    sa.UniqueConstraint('room_id', 'content_hash', name=op.f('uq_meeting_artifacts_room_id'))
    )
    op.create_index(op.f('ix_meeting_artifacts_room_id'), 'meeting_artifacts', ['room_id'], unique=False)
    op.create_table('meeting_attendees',
    sa.Column('room_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['meeting_rooms.id'], name=op.f('fk_meeting_attendees_room_id_meeting_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meeting_attendees_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id', name=op.f('pk_meeting_attendees'))
    )
    op.create_table('meeting_distributions',
    sa.Column('room_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('audience_key', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('resource_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['meeting_rooms.id'], name=op.f('fk_meeting_distributions_room_id_meeting_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_distributions')),
    sa.UniqueConstraint('room_id', 'revision', 'audience_key', name=op.f('uq_meeting_distributions_room_id'))
    )
    op.create_index(op.f('ix_meeting_distributions_room_id'), 'meeting_distributions', ['room_id'], unique=False)
    op.create_table('organization_changes',
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'preview'"), nullable=False),
    sa.Column('moves', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('action_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('preview','applied','undone')", name=op.f('ck_organization_changes_status')),
    sa.ForeignKeyConstraint(['action_id'], ['personal_actions.id'], name=op.f('fk_organization_changes_action_id_personal_actions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_organization_changes_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_changes'))
    )
    op.create_index(op.f('ix_organization_changes_owner_id'), 'organization_changes', ['owner_id'], unique=False)
    op.create_table('project_folders',
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('parent_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name=op.f('ck_project_folders_not_own_parent')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_project_folders_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id', 'owner_id', 'project_id'], ['project_folders.id', 'project_folders.owner_id', 'project_folders.project_id'], name='fk_project_folders_parent_scope', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'owner_id'], ['projects.id', 'projects.owner_id'], name='fk_project_folders_project_owner', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_folders')),
    sa.UniqueConstraint('id', 'owner_id', 'project_id', name='uq_project_folders_id_owner_project')
    )
    op.create_index('uq_project_folders_sibling_name', 'project_folders', ['project_id', 'parent_id', 'name'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_index(op.f('ix_project_folders_project_id'), 'project_folders', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_folders_owner_id'), 'project_folders', ['owner_id'], unique=False)
    op.create_table('workspace_automations',
    sa.Column('workspace_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('service_user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_user_id'], ['users.id'], name=op.f('fk_workspace_automations_service_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_automations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_automations')),
    sa.UniqueConstraint('service_user_id', name=op.f('uq_workspace_automations_service_user_id')),
    sa.UniqueConstraint('workspace_id', name=op.f('uq_workspace_automations_workspace_id'))
    )
    op.create_table('workspace_briefs',
    sa.Column('workspace_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'superseded')", name=op.f('ck_workspace_briefs_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workspace_briefs_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_briefs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_briefs')),
    sa.UniqueConstraint('workspace_id', 'revision', name='uq_workspace_briefs_revision')
    )
    op.create_index('uq_workspace_briefs_published', 'workspace_briefs', ['workspace_id'], unique=True, postgresql_where=sa.text("status = 'published'"))
    op.create_index(op.f('ix_workspace_briefs_workspace_id'), 'workspace_briefs', ['workspace_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('connection_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('calendar_id', sa.String(length=1024), nullable=False),
    sa.Column('provider_id', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('busy', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_calendar_events_connection_id_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_calendar_events_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_events')),
    sa.UniqueConstraint('connection_id', 'calendar_id', 'provider_id', name=op.f('uq_calendar_events_connection_id'))
    )
    op.create_index('ix_calendar_events_window', 'calendar_events', ['owner_id', 'starts_at', 'ends_at'], unique=False)
    op.create_index(op.f('ix_calendar_events_owner_id'), 'calendar_events', ['owner_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('connection_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('undo_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('email','teams')", name=op.f('ck_deliveries_channel')),
    sa.CheckConstraint("status IN ('pending','sending','sent','cancelled','failed','unknown')", name=op.f('ck_deliveries_status')),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_deliveries_connection_id_connections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_deliveries_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries')),
    sa.UniqueConstraint('owner_id', 'request_id', name=op.f('uq_deliveries_owner_id'))
    )
    op.create_index(op.f('ix_deliveries_owner_id'), 'deliveries', ['owner_id'], unique=False)
    op.create_index('ix_deliveries_due', 'deliveries', ['status', 'available_at'], unique=False)
    op.create_table('document_revisions',
    sa.Column('document_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('original_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('original_size', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=200), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('index_status', sa.String(length=24), nullable=False),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('indexed_count', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_token', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("index_status IN ('lexical_ready', 'vector_pending', 'indexing', 'ready', 'failed', 'disabled')", name=op.f('ck_document_revisions_index_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_document_revisions_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_revisions_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_revisions')),
    sa.UniqueConstraint('document_id', 'revision', name='uq_document_revisions_revision')
    )
    op.create_index(op.f('ix_document_revisions_document_id'), 'document_revisions', ['document_id'], unique=False)
    op.create_index('ix_document_revisions_index_queue', 'document_revisions', ['index_status', 'retry_at', 'lease_until'], unique=False)
    op.create_index('uq_document_revisions_current', 'document_revisions', ['document_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('job_revisions',
    sa.Column('job_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('submitted_by', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('decision', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['scheduled_jobs.id'], name=op.f('fk_job_revisions_job_id_scheduled_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_job_revisions_reviewed_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_job_revisions_submitted_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_revisions')),
    sa.UniqueConstraint('job_id', 'revision', name='uq_job_revisions_job_revision')
    )
    op.create_index(op.f('ix_job_revisions_job_id'), 'job_revisions', ['job_id'], unique=False)
    op.create_table('note_placements',
    sa.Column('note_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('folder_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id', 'owner_id', 'project_id'], ['project_folders.id', 'project_folders.owner_id', 'project_folders.project_id'], name='fk_note_placements_folder_scope', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id', 'owner_id'], ['notes.id', 'notes.owner_id'], name='fk_note_placements_note_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_note_placements_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', name=op.f('pk_note_placements'))
    )
    op.create_index(op.f('ix_note_placements_folder_id'), 'note_placements', ['folder_id'], unique=False)
    op.create_index(op.f('ix_note_placements_owner_id'), 'note_placements', ['owner_id'], unique=False)
    op.create_table('oauth_attempts',
    sa.Column('connection_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('encrypted_verifier', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_oauth_attempts_connection_id_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_attempts')),
    sa.UniqueConstraint('state_hash', name=op.f('uq_oauth_attempts_state_hash'))
    )
    op.create_index('ix_oauth_attempts_expiry', 'oauth_attempts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_attempts_connection_id'), 'oauth_attempts', ['connection_id'], unique=False)
    op.create_table('personal_captures',
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('note_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'saved'"), nullable=False),
    sa.Column('classification', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('classification_error', sa.String(length=500), nullable=True),
    sa.Column('classification_model', sa.String(length=200), nullable=True),
    sa.Column('explicit_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classification_token', sa.String(length=36), nullable=True),
    sa.Column('classification_lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('saved','classifying','classified','classification_failed','applied','undone')", name=op.f('ck_personal_captures_status')),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_personal_captures_note_id_notes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_personal_captures_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_captures')),
    sa.UniqueConstraint('id', 'owner_id', name='uq_personal_captures_id_owner'),
    sa.UniqueConstraint('owner_id', 'request_id', name='uq_personal_captures_owner_request')
    )
    op.create_index('ix_personal_captures_owner_created', 'personal_captures', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_personal_captures_note_id'), 'personal_captures', ['note_id'], unique=False)
    op.create_index(op.f('ix_personal_captures_owner_id'), 'personal_captures', ['owner_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('workspace_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('conversation_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('user_message_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('assistant_message_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('request_key', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=40), server_default=sa.text("'chat'"), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('stage', sa.String(length=60), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_token', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('context_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','succeeded','failed','cancelled')", name=op.f('ck_agent_runs_status')),
    sa.CheckConstraint('(lease_token IS NULL) = (lease_until IS NULL)', name=op.f('ck_agent_runs_lease_pair')),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['messages.id'], name=op.f('fk_agent_runs_assistant_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_agent_runs_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_agent_runs_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_agent_runs_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_message_id'], ['messages.id'], name=op.f('fk_agent_runs_user_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_agent_runs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs')),
    sa.UniqueConstraint('owner_id', 'request_key', name='uq_agent_runs_owner_request')
    )
    op.create_index('ix_agent_runs_claim', 'agent_runs', ['status', 'available_at', 'lease_until'], unique=False)
    op.create_index(op.f('ix_agent_runs_conversation_id'), 'agent_runs', ['conversation_id'], unique=False)
    op.create_index('uq_agent_runs_active_conversation', 'agent_runs', ['conversation_id'], unique=True, postgresql_where=sa.text("conversation_id IS NOT NULL AND status IN ('queued','running')"))
    op.create_index(op.f('ix_agent_runs_owner_id'), 'agent_runs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_workspace_id'), 'agent_runs', ['workspace_id'], unique=False)
    op.create_table('conversation_summaries',
    sa.Column('conversation_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('completed_turns', sa.Integer(), nullable=False),
    sa.Column('through_message_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_summaries_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['through_message_id'], ['messages.id'], name=op.f('fk_conversation_summaries_through_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_summaries')),
    sa.UniqueConstraint('conversation_id', 'completed_turns', name='uq_conversation_summaries_turns')
    )
    op.create_index(op.f('ix_conversation_summaries_conversation_id'), 'conversation_summaries', ['conversation_id'], unique=False)
    op.create_table('daily_checkins',
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('prompts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capture_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','completed','skipped')", name=op.f('ck_daily_checkins_status')),
    sa.ForeignKeyConstraint(['capture_id'], ['personal_captures.id'], name=op.f('fk_daily_checkins_capture_id_personal_captures'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_daily_checkins_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_checkins')),
    sa.UniqueConstraint('owner_id', 'local_date', name='uq_daily_checkins_owner_date')
    )
    op.create_index(op.f('ix_daily_checkins_owner_id'), 'daily_checkins', ['owner_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('revision_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, body)", persisted=True), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.VECTOR(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ordinal >= 0 AND start_offset >= 0 AND end_offset >= start_offset', name=op.f('ck_knowledge_chunks_offsets')),
    sa.ForeignKeyConstraint(['revision_id'], ['document_revisions.id'], name=op.f('fk_knowledge_chunks_revision_id_document_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks')),
    sa.UniqueConstraint('revision_id', 'ordinal', name='uq_knowledge_chunks_revision_ordinal')
    )
    op.create_index('ix_knowledge_chunks_embedding_1536', 'knowledge_chunks', [sa.literal_column('(embedding::vector(1536))').label('embedding_1536')], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding_1536': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_where=sa.text('vector_dims(embedding) = 1536'))
    op.create_index(op.f('ix_knowledge_chunks_revision_id'), 'knowledge_chunks', ['revision_id'], unique=False)
    op.create_index('ix_knowledge_chunks_search', 'knowledge_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('personal_tasks',
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('capture_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'proposed'"), nullable=False),
    sa.Column('suggested_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schedule_basis', sa.String(length=80), server_default=sa.text("'unscheduled'"), nullable=False),
    sa.Column('reminder_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed','open','done','dismissed')", name=op.f('ck_personal_tasks_status')),
    sa.ForeignKeyConstraint(['capture_id', 'owner_id'], ['personal_captures.id', 'personal_captures.owner_id'], name='fk_personal_tasks_capture_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_personal_tasks_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], name=op.f('fk_personal_tasks_reminder_id_reminders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_tasks')),
    sa.UniqueConstraint('capture_id', name='uq_personal_tasks_capture')
    )
    op.create_index(op.f('ix_personal_tasks_owner_id'), 'personal_tasks', ['owner_id'], unique=False)
    op.create_table('agent_checkpoint_writes',
    sa.Column('run_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('namespace', sa.String(length=200), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=100), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=200), nullable=False),
    sa.Column('payload_type', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_agent_checkpoint_writes_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'namespace', 'checkpoint_id', 'task_id', 'index', name=op.f('pk_agent_checkpoint_writes'))
    )
    op.create_table('agent_checkpoints',
    sa.Column('run_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('namespace', sa.String(length=200), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=100), nullable=True),
    sa.Column('payload_type', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_agent_checkpoints_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'namespace', 'checkpoint_id', name=op.f('pk_agent_checkpoints'))
    )
    op.create_table('agent_run_events',
    sa.Column('run_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_agent_run_events_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_run_events'))
    )
    op.create_index(op.f('ix_agent_run_events_run_id'), 'agent_run_events', ['run_id'], unique=False)
    op.create_check_constraint('ck_scheduled_jobs_approval_status','scheduled_jobs',"approval_status IN ('legacy','pending','approved','rejected')")
    op.create_check_constraint('ck_scheduled_jobs_task_type','scheduled_jobs',"task_type IN ('analysis','validation','handover','production_comparison','morning_brief')")
    op.create_check_constraint('ck_scheduled_jobs_dependency_policy','scheduled_jobs',"dependency_policy IN ('pass','pass_warn','any')")


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_run_events')
    op.drop_table('agent_checkpoints')
    op.drop_table('agent_checkpoint_writes')
    op.drop_table('personal_tasks')
    op.drop_table('knowledge_chunks')
    op.drop_table('daily_checkins')
    op.drop_table('conversation_summaries')
    op.drop_table('agent_runs')
    op.drop_table('personal_captures')
    op.drop_table('oauth_attempts')
    op.drop_table('note_placements')
    op.drop_table('job_revisions')
    op.drop_table('document_revisions')
    op.drop_table('deliveries')
    op.drop_table('calendar_events')
    op.drop_table('workspace_briefs')
    op.drop_table('workspace_automations')
    op.drop_table('project_folders')
    op.drop_table('organization_changes')
    op.drop_table('meeting_distributions')
    op.drop_table('meeting_attendees')
    op.drop_table('meeting_artifacts')
    op.drop_table('connections')
    op.drop_table('user_preferences')
    op.drop_table('scope_role_assignments')
    op.drop_table('personal_actions')
    op.drop_table('meeting_rooms')
    op.drop_table('assistant_settings')
    op.drop_column('reports', 'result_data')
    op.drop_column('job_runs', 'outcome')
    op.drop_column('scheduled_jobs', 'dependency_policy')
    op.drop_column('scheduled_jobs', 'activation_not_before')
    op.drop_column('scheduled_jobs', 'approved_revision')
    op.drop_column('scheduled_jobs', 'revision')
    op.drop_column('scheduled_jobs', 'approval_status')
    op.drop_column('scheduled_jobs', 'timezone')
    op.drop_column('scheduled_jobs', 'config')
    op.drop_column('scheduled_jobs', 'task_type')
    op.drop_constraint('fk_scheduled_jobs_execution_user_id_users','scheduled_jobs',type_='foreignkey')
    op.drop_column('scheduled_jobs', 'execution_user_id')
    op.drop_column('users', 'is_service')
    # ### end Alembic commands ###
