"""Durable bounded meeting extraction jobs; immutable schema snapshot."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '0003_meeting_extractions'
down_revision = '0002_agent_platform'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_extractions',
    sa.Column('room_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('requested_by', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('artifact_manifest', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('chunks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('cursor', sa.Integer(), nullable=False),
    sa.Column('partials', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('summary_work', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_token', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("phase IN ('map','reduce','finalize')", name=op.f('ck_meeting_extractions_phase')),
    sa.CheckConstraint("status IN ('queued','running','succeeded','failed','cancelled')", name=op.f('ck_meeting_extractions_status')),
    sa.CheckConstraint('(lease_until IS NULL) = (lease_token IS NULL)', name=op.f('ck_meeting_extractions_lease_pair')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_meeting_extractions_requested_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['meeting_rooms.id'], name=op.f('fk_meeting_extractions_room_id_meeting_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_extractions'))
    )
    op.create_index(op.f('ix_meeting_extractions_room_id'), 'meeting_extractions', ['room_id'], unique=False)
    op.create_index('ix_meeting_extractions_claim', 'meeting_extractions', ['status', 'available_at', 'lease_until'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('meeting_extractions')
