<script>
  import { onMount } from 'svelte';
  import { Activity, ArrowRight, Bell, BookOpen, Brain, Check, ChevronRight, CircleHelp, Clock, FileText, Folder, Layers, LockKeyhole, LogOut, Menu, MessageSquare, Plus, RefreshCw, Search, Settings, Shield, Sparkles, Users, X, Zap, AlertTriangle, Upload, CalendarClock, Play, Pause, Eye, Trash2, Pencil, Share2 } from 'lucide-svelte';
  import { api, setCSRF, query } from './api.js';
  import EntityForm from './EntityForm.svelte';
  import Modal from './Modal.svelte';
  import AgentChat from './components/AgentChat.svelte';
  import OptimusCapture from './components/OptimusCapture.svelte';
  import AssistantActivity from './components/AssistantActivity.svelte';
  import AssistantSettings from './components/AssistantSettings.svelte';
  import WorkspaceBrief from './components/WorkspaceBrief.svelte';
  import WorkspaceWizard from './components/WorkspaceWizard.svelte';
  import Connections from './components/Connections.svelte';
  import MeetingRooms from './components/MeetingRooms.svelte';
  import Setup from './components/Setup.svelte';
  import ScheduledWork from './components/ScheduledWork.svelte';
  import ReportView from './components/ReportView.svelte';
  import DocumentDetail from './components/DocumentDetail.svelte';
  import ProjectFolders from './components/ProjectFolders.svelte';

  let user = $state(null), boot = $state({ scopes: [], workspaces: [], projects: [], models: [], notifications: [], external_ai_enabled: false });
  let setupRequired = $state(false), wizard = $state(false), openedProject=$state(null),delegations=$state([]),hierarchyLabels=$state([]);
  let starting = $state(true), loginPending = $state(false), email = $state(''), password = $state(''), loginError = $state(''), loginNotice = $state('');
  let page = $state('assistant'), context = $state('personal'), mobileOpen = $state(false), loading = $state(false), error = $state(''), notice = $state('');
  let rows = $state([]), auxiliary = $state([]), members = $state([]), directory = $state([]), adminScopes = $state([]), audit = $state([]), grants = $state([]);
  let projectFilter = $state(''), searchText = $state(''), adminTab = $state('users'), subscriptionIds = $state([]), busy = $state(false);
  let modal = $state(null), modalBusy = $state(false), modalError = $state('');
  let uploadFile = $state(null), uploadInput = $state(null);
  let refreshSequence = 0;
  const noteKinds = ['observation','thought','hypothesis','decision','commitment','minutes'];
  const classifications = [{ value: 1, label: '1 · Internal' }, { value: 2, label: '2 · Confidential' }, { value: 3, label: '3 · Restricted' }];
  const personalNav = [{id:'assistant',label:'Optimus',icon:Sparkles},{id:'meetings',label:'Meeting Rooms',icon:Users},{ id:'notebook', label:'Notebook', icon:BookOpen },{ id:'projects',label:'Projects',icon:Folder },{id:'reminders',label:'Reminders',icon:Clock},{id:'memory',label:'Memory',icon:Brain},{id:'chat',label:'AI conversations',icon:Sparkles},{id:'documents',label:'Documents',icon:FileText},{id:'jobs',label:'Scheduled work',icon:CalendarClock},{id:'reports',label:'Reports',icon:Layers}];
  const workspaceNav = [{id:'brief',label:'Assistant brief',icon:Brain},{id:'connections',label:'Connections',icon:Zap},{id:'overview',label:'Overview',icon:Layers},{id:'chat',label:'Conversations',icon:MessageSquare},{id:'documents',label:'Documents',icon:FileText},{id:'incidents',label:'Incidents',icon:AlertTriangle},{id:'jobs',label:'Scheduled work',icon:CalendarClock},{id:'reports',label:'Reports',icon:BookOpen},{id:'members',label:'Members',icon:Users}];
  const titles = {assistant:'Good work starts with clarity',activity:'Assistant activity',preferences:'Assistant preferences',connections:'Connections',meetings:'Meeting Rooms',brief:'Workspace brief',notebook:'Your notebook',projects:'Your projects',reminders:'Reminders',memory:'Your memory',chat:'AI conversations',documents:'Documents',jobs:'Scheduled work',reports:'Reports',overview:'Workspace overview',incidents:'Incidents',members:'Workspace members',publications:'Published summaries',notifications:'Notifications',admin:'Administration'};
  const descriptions = {assistant:'Capture a thought, prepare for a decision, and keep track of what comes next.',activity:'Review and reverse the automatic changes Optimus made for you.',preferences:'Choose how your assistant responds and when it should take initiative.',connections:'Bring your approved data and work systems into context.',meetings:'Prepare, capture decisions, and follow through on agreed actions.',brief:'The shared instructions and context for every assistant run in this workspace.',notebook:'Capture observations, decisions, and the details you want to come back to.',projects:'Give your notes and documents a shared purpose.',reminders:'Follow through on commitments, at the right time.',memory:'Review the context you have explicitly chosen to remember.',chat:'Work through questions with the models configured for your installation.',documents:'Upload source material for this space and inspect its extracted text.',jobs:'Schedule real AI work and follow each execution.',reports:'Completed work, ready to read and use.',overview:'A common place for source material, conversations, and decisions.',incidents:'Coordinate acknowledgement, resolution, and permitted summaries.',members:'People with explicit access to this workspace.',publications:'Summaries authorized by your scope access.',notifications:'Updates and reminders you are authorized to receive.',admin:'Manage identities, organizational scopes, and access.'};
  let workspace = $derived(boot.workspaces?.find(w => w.id === context));
  let isShared = $derived(context !== 'personal');
  let canManage = $derived(workspace?.membership_role === 'manager');
  let canWrite = $derived(!isShared || ['manager','member'].includes(workspace?.membership_role));
  let cloudAllowed = $derived(boot.external_ai_enabled && (!isShared || workspace?.external_ai_enabled));
  let unread = $derived((boot.notifications || []).filter(n => !n.read_at).length);
  let projectOptions = $derived((boot.projects || []).filter(p => !p.archived).map(p => ({value:p.id,label:p.name})));
  let scopeOptions = $derived((adminScopes.length ? adminScopes : boot.scopes || []).map(s => ({value:s.id,label:s.name})));
  let userOptions = $derived(directory.filter(u=>u.active!==false).map(u => ({value:u.id,label:`${u.name} · ${u.email}`})));

  const fmt = value => value ? new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}) : '—';
  const shortDate = value => value ? new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric'}) : '—';
  const titleCase = text => String(text || '').replaceAll('_',' ').replace(/^./,s=>s.toUpperCase());
  const idLabel = id => directory.find(u=>u.id===id)?.name || members.find(m=>m.user_id===id)?.name || id || 'Unassigned';
  const asOptions = values => values.map(v=>({value:v,label:titleCase(v)}));
  const localDate = value => { const d = value ? new Date(value) : new Date(Date.now()+3600000); return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16); };
  const utcDate = value => new Date(value).toISOString();
  const scopeName = id => (adminScopes.length ? adminScopes : boot.scopes || []).find(s=>s.id===id)?.name || 'Organizational scope';
  const contextBody = () => isShared ? {workspace_id:context} : (projectFilter ? {project_id:projectFilter} : {});
  const contextQuery = () => query(contextBody());
  function fail(e) { error = e.message; if (e.status === 401) { user = null; setCSRF(''); loginError='Your session ended. Sign in to continue.'; } }
  async function refreshBootstrap() { const result = await api('/bootstrap'); boot = result; user = result.user || user; }
  async function init() { try { const setup = await api('/setup/status');setupRequired=setup.required;if(setupRequired)return;const auth = await api('/auth/me'); user=auth.user; setCSRF(auth.csrf_token); await refreshBootstrap(); await loadView(); } catch(e) { if (e.status!==401) {if(user)error=e.message;else loginError=e.message;} } finally { starting=false; } }
  onMount(init);
  async function setupComplete(auth){setupRequired=false;user=auth.user;setCSRF(auth.csrf_token);await refreshBootstrap();await loadView();}
  async function login(event) { event.preventDefault(); loginPending=true; loginError=''; try { const auth=await api('/auth/login',{method:'POST',body:{email,password}}); rows=[];auxiliary=[];members=[];directory=[];adminScopes=[];audit=[];grants=[];projectFilter='';searchText='';context='personal';page='assistant';loading=true;user=auth.user;setCSRF(auth.csrf_token);password='';loginNotice=''; await refreshBootstrap(); await loadView(); } catch(e) {if(user){fail(e);loading=false;}else loginError=e.message;} finally {loginPending=false;} }
  async function logout() { await act(async()=>{await api('/auth/logout',{method:'POST'}); user=null; setCSRF(''); boot={scopes:[],workspaces:[],projects:[],models:[],notifications:[],external_ai_enabled:false}; rows=[]; directory=[]; context='personal'; page='assistant';},'Signed out.',false); }
  async function navigate(next, nextContext=context) { page=next; context=nextContext; mobileOpen=false; error=''; notice=''; rows=[]; auxiliary=[]; if(nextContext!=='personal') projectFilter=''; await loadView(); }
  async function loadView() {
    const seq=++refreshSequence; loading=true; error='';
    const activeContext=context, activePage=page;
    try {
      let result=[], extra=[];
      if(page==='notebook') result=await api('/notes'+query({project_id:projectFilter,q:searchText}));
      else if(page==='projects') result=await api('/projects');
      else if(page==='reminders') result=await api('/reminders');
      else if(page==='memory') result=await api('/memories');
      else if(page==='documents') result=await api('/documents'+contextQuery());
      else if(page==='incidents') { [result,members]=await Promise.all([api('/incidents'+query({workspace_id:context})),api(`/workspaces/${context}/members`)]); }
      else if(page==='members') { result=await api(`/workspaces/${context}/members`); members=result; if(canManage) directory=await api('/directory'); }
      else if(page==='overview') { [result,extra]=await Promise.all([api('/incidents'+query({workspace_id:context})),api('/documents'+contextQuery())]); }


      else if(page==='reports') { const all=await api('/reports'+contextQuery()); result=all.filter(r=>isShared ? r.workspace_id===context : !r.workspace_id); }
      else if(page==='publications') result=await api('/publications');
      else if(page==='notifications') { [result,extra]=await Promise.all([api('/notifications'),api('/subscriptions')]); subscriptionIds=(Array.isArray(extra) ? extra.map(s=>typeof s==='string'?s:s.scope_id) : extra?.scope_ids || []).filter(id=>(boot.reviewable_scope_ids||[]).includes(id)); }
      else if(page==='admin') { const [users,scopes,events,scopeGrants]=await Promise.all([api('/admin/users'),api('/admin/scopes'),api('/admin/audit'),api('/admin/scope-grants')]); result=users; directory=users; adminScopes=scopes; audit=events; grants=scopeGrants;[delegations,hierarchyLabels]=await Promise.all([api('/admin/delegations'),api('/hierarchy-labels')]);hierarchyLabels=hierarchyLabels.labels; }
      if(seq===refreshSequence && context===activeContext && page===activePage) { rows=result || []; auxiliary=extra || []; }
    } catch(e) { if(seq===refreshSequence) fail(e); } finally { if(seq===refreshSequence) loading=false; }
  }
  async function act(fn, success='Saved.', reload=true) { if(busy) return; busy=true; error=''; try { await fn(); notice=success; if(reload) {await refreshBootstrap(); await loadView();} } catch(e) {fail(e);} finally {busy=false;} }
  function showForm(title,fields,initial,onSubmit,description='',label='Save') { modal={title,fields,initial,onSubmit,description,label}; modalError=''; }
  async function saveForm(values) { modalBusy=true; modalError=''; try {await modal.onSubmit(values); modal=null; notice='Saved successfully.'; if(user){try{await refreshBootstrap(); await loadView();}catch(e){fail(e);}}} catch(e) {if(e.status===401){fail(e);modal=null;}else modalError=e.message;} finally {modalBusy=false;} }
  function closeModal() { if(!modalBusy) modal=null; }
  async function ensureDirectory() { directory=await api('/directory'); }
  const projectField=()=>({key:'project_id',label:'Project',type:'select',placeholder:'No project',options:projectOptions});
  function noteForm(note=null) { showForm(note?'Edit note':'Capture a note',[{key:'title',label:'Title',maxlength:160},{key:'body',label:'Note',type:'textarea',required:true,rows:8},{key:'kind',label:'Kind',type:'select',options:asOptions(noteKinds),required:true},projectField()],note?{...note,project_id:note.project_id||''}:{title:'',body:'',kind:'observation',project_id:projectFilter},v=>api('/notes'+(note?`/${note.id}`:''),{method:note?'PATCH':'POST',body:{...v,title:v.title||v.body.slice(0,72),project_id:v.project_id||null}}),'Your notebook is private to you.'); }
  function projectForm(project=null) { showForm(project?'Edit project':'New project',[{key:'name',label:'Project name',required:true,maxlength:160},{key:'goal',label:'Goal',type:'textarea'}],project||{name:'',goal:''},v=>api('/projects'+(project?`/${project.id}`:''),{method:project?'PATCH':'POST',body:v})); }
  function memoryForm(note=null,memory=null) { showForm(memory?'Edit remembered context':'Remember from this note',[{key:'text',label:'Context to remember',type:'textarea',required:true,maxlength:4000}],{text:memory?.text||note?.body||''},v=>api('/memories'+(memory?`/${memory.id}`:''),{method:memory?'PATCH':'POST',body:memory?v:{...v,note_id:note.id}}),'Memory is derived context. Forgetting it keeps the original note.'); }
  function reminderForm(note) { showForm('Create reminder',[{key:'title',label:'Reminder',required:true},{key:'due_at',label:'Due date and time',type:'datetime-local',required:true}],{title:note.title||'Review note',due_at:localDate()},v=>api('/reminders',{method:'POST',body:{...v,note_id:note.id,due_at:utcDate(v.due_at)}})); }
  function snoozeForm(reminder) { showForm('Snooze reminder',[{key:'due_at',label:'Remind me at',type:'datetime-local',required:true}],{due_at:localDate()},v=>api(`/reminders/${reminder.id}`,{method:'PATCH',body:{status:'snoozed',due_at:utcDate(v.due_at)}})); }
  async function workspaceForm(existing=null) {try{if(!existing){if(user.is_admin)adminScopes=await api('/admin/scopes');wizard=true;return;}showForm('Workspace settings',[{key:'name',label:'Workspace name',required:true},{key:'description',label:'Purpose',type:'textarea'},{key:'external_ai_enabled',label:'Allow external AI for this workspace',type:'check',help:'Members also confirm before the assistant uses conversation context.'}],existing,v=>api(`/workspaces/${existing.id}`,{method:'PATCH',body:v}),'Configure assistant instructions in the Workspace brief tab.');}catch(e){fail(e);}}
  async function memberForm() { try {await ensureDirectory(); showForm('Add workspace member',[{key:'user_id',label:'Person',type:'select',options:userOptions,required:true,placeholder:'Choose a person'},{key:'role',label:'Role',type:'select',options:asOptions(['viewer','member','manager']),required:true}],{user_id:'',role:'member'},v=>api(`/workspaces/${context}/members`,{method:'POST',body:v}),'Viewer reads; member contributes; manager configures access.');}catch(e){fail(e);} }
  async function incidentForm(note=null) {
    try { await ensureDirectory(); const targets=(boot.workspaces||[]).filter(w=>['member','manager'].includes(w.membership_role));
      const fields=[...(note?[{key:'workspace_id',label:'Destination workspace',type:'select',options:targets.map(w=>({value:w.id,label:w.name})),placeholder:'Choose a workspace',required:true}]:[]),{key:'title',label:'Title',required:true},{key:'summary',label:note?'Exact excerpt to share':'Summary',type:'textarea',required:true,help:note?'Copy only the passage you intend to share from the source below. The excerpt must exactly match text in your note.':undefined},{key:'severity',label:'Severity',type:'select',options:asOptions(['low','medium','high','critical']),required:true},{key:'assignee_id',label:'Assignee',type:'select',options:userOptions,required:true,placeholder:'Choose a workspace contributor',help:'The assignee must be a member or manager of the destination workspace.'},{key:'decision',label:'Decision or next action',type:'textarea',required:true},...((note||canManage)?[{key:'published',label:'Publish summary to authorized scope readers',type:'check',help:'Only a manager of the destination workspace may publish.'}]:[])];
      const requestId=crypto.randomUUID();
      showForm(note?'Share a selected excerpt':'Report an incident',fields,{workspace_id:note?(targets[0]?.id||''):context,title:note?.title||'',summary:'',severity:'medium',assignee_id:user.id,decision:'',published:false},v=>{if(note&&!note.body.includes(v.summary))throw new Error('The excerpt must exactly match a passage in the original note.');return api('/incidents',{method:'POST',body:{published:false,...v,workspace_id:v.workspace_id||context,request_id:requestId,...(note?{note_id:note.id}:{})}});},note?`Original private note:\n${note.body}`:'Keep the summary appropriate for its intended audience.');
    }catch(e){fail(e);}
  }
  function incidentAction(incident,action) { showForm(`${titleCase(action)} incident`,[{key:'reason',label:action==='resolve'?'Resolution':'Reason or context',type:'textarea',required:action==='resolve'||action==='escalate'}],{reason:''},v=>api(`/incidents/${incident.id}/actions`,{method:'POST',body:{action,...v}}),action==='publish'?'This summary becomes available to authorized readers of its organizational scope.':action==='escalate'?'Critical escalations may reach authorized ancestor-scope readers.':incident.title,titleCase(action)); }
  async function upload(event) {event.preventDefault();if(!uploadFile)return;await act(async()=>{const data=new FormData();data.append('file',uploadFile);Object.entries(contextBody()).forEach(([k,v])=>data.append(k,v));await api('/documents',{method:'POST',body:data});uploadFile=null;if(uploadInput)uploadInput.value='';},'Document uploaded and extracted.');}
  async function viewDocument(doc) {try {const result=await api(`/documents/${doc.id}`);modal={title:result.title||result.filename,document:result,description:`${result.media_type || 'Extracted document'} · ${isShared?'Workspace':'Private'} source`};}catch(e){fail(e);} }
  async function deleteItem(path,label) {if(!window.confirm(label))return;await act(()=>api(path,{method:'DELETE'}),'Removed.');}
  function userForm() {showForm('Create user',[{key:'name',label:'Full name',required:true},{key:'email',label:'Email',type:'email',required:true},{key:'password',label:'Initial password',type:'password',required:true,minlength:12,autocomplete:'new-password',help:'Use at least 12 characters; share the password through an approved secure channel.'},{key:'clearance',label:'Clearance',type:'select',options:classifications},{key:'is_admin',label:'Installation administrator',type:'check'}],{name:'',email:'',password:'',clearance:1,is_admin:false},v=>api('/admin/users',{method:'POST',body:{...v,clearance:Number(v.clearance)}}));}
  function editUser(u) {showForm('Edit user access',[{key:'clearance',label:'Clearance',type:'select',options:classifications},{key:'active',label:'Active account',type:'check'}],{clearance:u.clearance,active:u.active},v=>api(`/admin/users/${u.id}`,{method:'PATCH',body:{...v,clearance:Number(v.clearance)}}),`${u.name} · ${u.email}`);}
  function scopeForm() {showForm('Create organizational scope',[{key:'name',label:'Scope name',required:true},{key:'kind',label:'Scope type',required:true,maxlength:40,placeholder:'For example: enterprise, region, site, or team',help:'Use the terminology your organization uses.'},{key:'parent_id',label:'Parent scope',type:'select',options:scopeOptions,placeholder:'Top level'}],{name:'',kind:'site',parent_id:''},v=>api('/admin/scopes',{method:'POST',body:{...v,parent_id:v.parent_id||null}}),'Use scopes to organize summary access. Workspace membership is managed separately.');}
  function grantForm() {showForm('Grant summary access',[{key:'user_id',label:'Person',type:'select',options:userOptions,required:true,placeholder:'Choose a person'},{key:'scope_id',label:'Scope',type:'select',options:scopeOptions,required:true,placeholder:'Choose a scope'}],{user_id:'',scope_id:''},v=>api('/admin/scope-grants',{method:'POST',body:v}),'A grant permits summaries for this scope and direct children, plus explicit critical escalations from descendants. It does not grant raw workspace access.');}
  function delegationForm(){showForm('Delegate scoped responsibility',[{key:'user_id',label:'Person',type:'select',options:userOptions,required:true,placeholder:'Choose a person'},{key:'scope_id',label:'Scope',type:'select',options:scopeOptions,required:true,placeholder:'Choose a scope'},{key:'manage_workspaces',label:'Create workspaces within this scope',type:'check'},{key:'manage_people',label:'Manage people within this scope',type:'check'},{key:'effective_until',label:'Expiry (optional)',type:'datetime-local'}],{user_id:'',scope_id:'',manage_workspaces:true,manage_people:false,effective_until:''},v=>api('/admin/delegations',{method:'POST',body:{...v,effective_until:v.effective_until?utcDate(v.effective_until):null}}));}
  function passwordForm() {showForm('Change your password',[{key:'current_password',label:'Current password',type:'password',required:true,autocomplete:'current-password'},{key:'new_password',label:'New password',type:'password',required:true,minlength:12,autocomplete:'new-password'}],{current_password:'',new_password:''},async v=>{await api('/auth/password',{method:'POST',body:v});user=null;setCSRF('');loginNotice='Password changed. Sign in with your new password.';loginError='';},'Use at least 12 characters.');}
</script>

<svelte:head><title>{user ? `${titles[page]} · V-OptimAIse` : 'Sign in · V-OptimAIse'}</title></svelte:head>
{#if starting}
  <div class="initial-loading"><span class="brandmark"><Zap size={25}/></span><h1>V-OptimAIse</h1><p>Connecting to your installation…</p></div>
{:else if setupRequired}<Setup complete={setupComplete}/>
{:else if !user}
  <div class="login-shell">
    <section class="login-story"><div class="brand"><span class="brandmark"><Zap size={25}/></span><span>V-OptimAIse<small>ENTERPRISE WORKSPACE</small></span></div><div class="login-copy"><span class="eyebrow">KNOWLEDGE. CONTEXT. ACTION.</span><h1>Better decisions<br/>start with<br/><em>shared understanding.</em></h1><p>Your private thinking and your team’s operational work, connected with purpose.</p></div><div class="login-footer"><LockKeyhole size={16}/> Self-hosted workspace · Explicit access controls</div></section>
    <main class="login-main"><div class="login-form"><span class="eyebrow">WELCOME TO YOUR WORKSPACE</span><h2>Sign in</h2><p>Use the account provided by your administrator.</p>{#if loginNotice}<div class="banner success" role="status">{loginNotice}</div>{/if}<form onsubmit={login}><label>Email address<input type="email" bind:value={email} required autocomplete="username" placeholder="you@company.com" disabled={loginPending}/></label><label>Password<input type="password" bind:value={password} required autocomplete="current-password" disabled={loginPending}/></label>{#if loginError}<p class="form-error" role="alert">{loginError}</p>{/if}<button class="button primary wide" disabled={loginPending}>{loginPending?'Signing in…':'Sign in to workspace'}<ArrowRight size={17}/></button></form><div class="setup-note"><Shield size={18}/><p>Contact your installation administrator if you need an account.</p></div></div></main>
  </div>
{:else}
  <div class="app">
    {#if mobileOpen}<button class="sidebar-scrim" onclick={()=>mobileOpen=false} aria-label="Close navigation"></button>{/if}
    <aside class:mobile-open={mobileOpen} class="sidebar">
      <div class="brand"><span class="brandmark"><Zap size={23}/></span><span>V-OptimAIse<small>ENTERPRISE WORKSPACE</small></span></div>
      <button class="space-switch" class:selected={context==='personal'} onclick={()=>navigate('assistant','personal')}><span class="avatar">{user.name?.slice(0,1).toUpperCase()||'U'}</span><span>My Assistant<small>Notes, context, follow-through</small></span><LockKeyhole size={14}/></button>
      <div class="side-label">MY WORK</div>
      <nav aria-label="Personal workspace">{#each personalNav as item}<button class="nav-item" class:active={page===item.id&&context==='personal'} onclick={()=>navigate(item.id,'personal')}><item.icon size={17}/><span>{item.label}</span></button>{/each}</nav>
      <div class="side-section"><span class="side-label">SHARED WORKSPACES</span>{#if user.is_admin||boot.can_create_workspace}<button class="icon-button" title="Create workspace" aria-label="Create workspace" onclick={()=>workspaceForm()}><Plus size={16}/></button>{/if}</div>
      <nav aria-label="Shared workspaces">{#each boot.workspaces || [] as space}<button class="nav-item workspace-link" class:active={context===space.id&&!['admin','publications','notifications'].includes(page)} onclick={()=>navigate('overview',space.id)}><span class="workspace-dot">{space.name.slice(0,1)}</span><span>{space.name}</span></button>{:else}<p class="side-empty">Your shared workspaces will appear here.</p>{/each}</nav>
      <div class="side-section"><span class="side-label">ACCOUNT</span></div>
      <nav aria-label="Account"><button class="nav-item" class:active={page==='connections'&&!isShared} onclick={()=>navigate('connections','personal')}><Zap size={17}/>My connections</button><button class="nav-item" class:active={page==='notifications'} onclick={()=>navigate('notifications','personal')}><Bell size={17}/>Notifications{#if unread}<span class="count">{unread}</span>{/if}</button><button class="nav-item" class:active={page==='activity'} onclick={()=>navigate('activity','personal')}><Activity size={17}/>Assistant activity</button><button class="nav-item" class:active={page==='preferences'} onclick={()=>navigate('preferences','personal')}><Settings size={17}/>Preferences</button></nav>
      <div class="side-section"><span class="side-label">ORGANIZATION</span></div>
      <nav aria-label="Organization"><button class="nav-item" class:active={page==='publications'} onclick={()=>navigate('publications','personal')}><Layers size={17}/>Published summaries</button>{#if user.is_admin}<button class="nav-item" class:active={page==='admin'} onclick={()=>navigate('admin','personal')}><Shield size={17}/>Administration</button>{/if}</nav>
      <div class="sidebar-bottom"><div class="profile"><span class="avatar">{user.name?.slice(0,1).toUpperCase()||'U'}</span><span><strong>{user.name}</strong><small>{user.is_admin?'Administrator':'Team member'}</small></span><button class="icon-button" title="Change password" aria-label="Change password" onclick={passwordForm}><Settings size={16}/></button><button class="icon-button" title="Sign out" aria-label="Sign out" onclick={logout} disabled={busy}><LogOut size={16}/></button></div></div>
    </aside>
    <div class="main-shell">
      <header class="topbar"><div class="breadcrumb"><button class="icon-button mobile-toggle" aria-label="Open navigation" onclick={()=>mobileOpen=true}><Menu size={21}/></button><span>{['admin','publications','notifications'].includes(page)?'Organization':isShared?'Shared workspace':'Private space'}</span><ChevronRight size={14}/><strong>{workspace?.name||titles[page]}</strong></div><div class="top-actions"><span class="privacy-pill">{#if isShared}<Users size={13}/>Explicit membership{:else}<LockKeyhole size={13}/>Private by default{/if}</span><button class="icon-button" aria-label="Refresh current view" title="Refresh" onclick={()=>act(async()=>{},'Up to date.')} disabled={loading||busy}><RefreshCw size={17}/></button><button class="notification-button icon-button" aria-label={`Notifications${unread?`, ${unread} unread`:''}`} onclick={()=>navigate('notifications','personal')}><Bell size={19}/>{#if unread}<i></i>{/if}</button></div></header>
      <main>
        <div class="page-heading"><div><span class="eyebrow">{isShared?`${scopeName(workspace?.scope_id)} / SHARED KNOWLEDGE`:'A CLEARER WAY TO WORK'}</span><h1>{page==='overview'?workspace?.name:page==='connections'&&!isShared?'My connections':titles[page]}</h1><p>{page==='overview'?workspace?.description||descriptions[page]:descriptions[page]}</p></div><div class="heading-actions">
          {#if page==='notebook'}<button class="button primary" onclick={()=>noteForm()}><Plus size={16}/>Capture note</button>
          {:else if page==='projects'}<button class="button primary" onclick={()=>projectForm()}><Plus size={16}/>New project</button>
          {:else if page==='incidents'&&canWrite}<button class="button primary" onclick={()=>incidentForm()}><Plus size={16}/>Report incident</button>
          {:else if page==='members'&&canManage}<button class="button primary" onclick={memberForm}><Plus size={16}/>Add member</button>
          {:else if page==='overview'&&canManage}<button class="button" onclick={()=>workspaceForm(workspace)}><Settings size={16}/>Settings</button>{/if}
        </div></div>
        {#if isShared}<div class="workspace-tabs" role="navigation" aria-label="Workspace sections">{#each workspaceNav as item}<button class:chosen={page===item.id} onclick={()=>navigate(item.id)}><item.icon size={15}/>{item.label}</button>{/each}</div>{/if}
        {#if error}<div class="banner error" role="alert"><AlertTriangle size={19}/><p>{error}</p><button class="icon-button" aria-label="Dismiss error" onclick={()=>error=''}><X size={16}/></button></div>{/if}
        {#if notice}<div class="banner success" role="status"><Check size={18}/><p>{notice}</p><button class="icon-button" aria-label="Dismiss message" onclick={()=>notice=''}><X size={16}/></button></div>{/if}
        {#if !boot.workspaces?.length && user.is_admin && ['assistant','notebook'].includes(page)}<section class="onboarding"><div class="onboarding-title"><span class="feature-icon"><Layers size={24}/></span><div><span class="eyebrow">BUILD YOUR SHARED WORKSPACE</span><h2>A clean start for your organization</h2><p>Capture your first private note below, or set up a shared space.</p></div></div><div class="onboarding-steps"><button onclick={()=>{adminTab='scopes';navigate('admin','personal');}}><span>01</span><strong>Define your structure</strong><small>Create an organizational scope.</small><ArrowRight size={17}/></button><button onclick={()=>{adminTab='users';navigate('admin','personal');}}><span>02</span><strong>Add your people</strong><small>Create accounts and clearances.</small><ArrowRight size={17}/></button><button onclick={()=>workspaceForm()}><span>03</span><strong>Open a workspace</strong><small>Invite members to shared work.</small><ArrowRight size={17}/></button></div></section>{/if}
        {#if loading}<div class="loading" role="status"><RefreshCw size={23}/><p>Loading {titles[page]?.toLowerCase()}…</p></div>
        {:else if page==='assistant'}<OptimusCapture projects={boot.projects||[]} onSaved={refreshBootstrap}/>
        {:else if page==='activity'}<AssistantActivity/>
        {:else if page==='preferences'}<AssistantSettings/>
        {:else if page==='connections'}{#key context}<Connections workspaceId={isShared?context:null} canManage={!isShared||canManage} isAdmin={user.is_admin} workspaces={boot.workspaces||[]}/>{/key}
        {:else if page==='meetings'}<MeetingRooms workspaces={boot.workspaces||[]} {user}/>
        {:else if page==='brief'}{#key context}<WorkspaceBrief {workspace} {canManage} onSaved={refreshBootstrap}/>{/key}
        {:else if page==='notebook'}
          <div class="toolbar"><form class="search" onsubmit={e=>{e.preventDefault();loadView();}}><Search size={17}/><input aria-label="Search notes" bind:value={searchText} placeholder="Search your notes…"/><button class="button compact">Search</button></form><label class="inline-label">Project<select bind:value={projectFilter} onchange={loadView}><option value="">All projects</option>{#each projectOptions as p}<option value={p.value}>{p.label}</option>{/each}</select></label></div>
          <div class="section-heading"><h2>Collected thoughts <span class="subtle-count">{rows.length}</span></h2><span class="muted"><LockKeyhole size={13}/> Yours to shape and share</span></div>
          <div class="notes-grid">{#each rows as note}<article class="note-card"><header><span class="tag">{titleCase(note.kind)}</span><time>{shortDate(note.updated_at||note.created_at)}</time></header><h3>{note.title||'Untitled note'}</h3><p class="note-body">{note.body}</p>{#if note.project_id}<span class="project-label"><Folder size={13}/>{boot.projects.find(p=>p.id===note.project_id)?.name||'Project'}</span>{/if}<footer><button class="text-button" onclick={()=>noteForm(note)}><Pencil size={14}/>Edit</button><button class="text-button" onclick={()=>memoryForm(note)}><Brain size={14}/>Remember</button><button class="text-button" onclick={()=>reminderForm(note)}><Clock size={14}/>Remind</button><button class="text-button" onclick={()=>incidentForm(note)}><Share2 size={14}/>Share excerpt</button></footer></article>{:else}<div class="empty card wide-grid"><span class="feature-icon"><BookOpen size={27}/></span><h2>Make room for your next good thought.</h2><p>Add an observation, a decision, or something worth remembering.</p><button class="button primary" onclick={()=>noteForm()}><Plus size={16}/>Capture your first note</button></div>{/each}</div>
        {:else if page==='projects'}
          <div class="card-grid">{#each rows as project}<article class="card project-card"><span class="feature-icon"><Folder size={24}/></span><span class="tag float-tag">{project.archived?'Archived':'Active'}</span><h2>{project.name}</h2><p>{project.goal||'No goal added yet.'}</p><footer><button class="text-button" onclick={()=>{projectFilter=project.id;navigate('notebook','personal');}}>Open notebook<ArrowRight size={15}/></button><button class="text-button" onclick={()=>openedProject=project}><Folder size={14}/>Folders</button><button class="icon-button" title="Edit project" aria-label={`Edit ${project.name}`} onclick={()=>projectForm(project)}><Pencil size={16}/></button><button class="text-button" disabled={busy} onclick={()=>act(()=>api(`/projects/${project.id}`,{method:'PATCH',body:{archived:!project.archived}}),project.archived?'Project restored.':'Project archived.')}>{project.archived?'Restore':'Archive'}</button></footer></article>{:else}<div class="empty card wide-grid"><Folder size={30}/><h2>Start with a purpose.</h2><p>A project brings related notes and documents together.</p><button class="button primary" onclick={()=>projectForm()}>Create your first project</button></div>{/each}</div>
          {#if openedProject}{#key openedProject.id}<ProjectFolders project={openedProject} close={()=>openedProject=null}/>{/key}{/if}
        {:else if page==='memory'}
          <div class="info-strip"><Brain size={19}/><p>Memory contains only the context you explicitly saved. Forgetting a memory leaves its source note intact.</p></div><div class="stack">{#each rows as memory}<article class="card row-card"><span class="feature-icon"><Brain size={21}/></span><div class="grow"><p class="pre-wrap">{memory.text}</p><small class="muted">Saved {fmt(memory.created_at)}</small></div><button class="icon-button" aria-label="Edit memory" onclick={()=>memoryForm(null,memory)}><Pencil size={17}/></button><button class="button" disabled={busy} onclick={()=>deleteItem(`/memories/${memory.id}`,'Forget this derived memory? Your original note will be retained.')}>Forget</button></article>{:else}<div class="empty card"><Brain size={30}/><h2>Context you choose to keep.</h2><p>Open a note and select Remember to add it here.</p><button class="button" onclick={()=>navigate('notebook','personal')}>Go to notebook<ArrowRight size={15}/></button></div>{/each}</div>
        {:else if page==='reminders'}
          <div class="stack">{#each rows as reminder}<article class="card row-card"><span class="feature-icon"><Clock size={21}/></span><div class="grow"><h3>{reminder.title}</h3><p class="muted">{fmt(reminder.due_at)}</p></div><span class="tag" class:green={reminder.status==='done'}>{titleCase(reminder.status)}</span>{#if !['done','cancelled'].includes(reminder.status)}<button class="button" onclick={()=>snoozeForm(reminder)}>Snooze</button><button class="button" disabled={busy} onclick={()=>act(()=>api(`/reminders/${reminder.id}`,{method:'PATCH',body:{status:reminder.status==='waiting'?'open':'waiting'}}))}>{reminder.status==='waiting'?'Reopen':'Waiting'}</button><button class="button primary" disabled={busy} onclick={()=>act(()=>api(`/reminders/${reminder.id}`,{method:'PATCH',body:{status:'done'}}),'Reminder completed.')}><Check size={15}/>Done</button><button class="icon-button" aria-label="Cancel reminder" disabled={busy} onclick={()=>act(()=>api(`/reminders/${reminder.id}`,{method:'PATCH',body:{status:'cancelled'}}),'Reminder cancelled.')}><X size={16}/></button>{:else}<button class="button" disabled={busy} onclick={()=>act(()=>api(`/reminders/${reminder.id}`,{method:'PATCH',body:{status:'open'}}),'Reminder reopened.')}>Reopen</button>{/if}</article>{:else}<div class="empty card"><Clock size={30}/><h2>Keep the next step in sight.</h2><p>Create a reminder from any note in your notebook.</p><button class="button" onclick={()=>navigate('notebook','personal')}>Go to notebook<ArrowRight size={15}/></button></div>{/each}</div>
        {:else if page==='overview'}
          <section class="workspace-brief"><div><span class="eyebrow">A SHARED SOURCE OF UNDERSTANDING</span><h2>Turn knowledge into coordinated action.</h2><p>Bring source documents, AI conversations, and incident decisions into one workspace.</p><button class="button primary" onclick={()=>navigate('chat')}><Sparkles size={16}/>Start a conversation</button></div><div class="workspace-seal"><Layers size={56}/><span>CLASSIFICATION {workspace?.classification}</span></div></section><div class="metrics"><button onclick={()=>navigate('incidents')}><AlertTriangle size={21}/><strong>{rows.filter(i=>i.status!=='resolved').length}</strong><span>Open incidents</span></button><button onclick={()=>navigate('documents')}><FileText size={21}/><strong>{auxiliary.length}</strong><span>Source documents</span></button><button onclick={()=>navigate('members')}><Shield size={21}/><strong>{titleCase(workspace?.membership_role||'Member')}</strong><span>Your workspace role</span></button></div><div class="section-heading"><h2>Needs attention</h2><button class="text-button" onclick={()=>navigate('incidents')}>All incidents<ArrowRight size={15}/></button></div><div class="stack">{#each rows.filter(i=>i.status!=='resolved').slice(0,5) as incident}<article class="card row-card"><span class="feature-icon"><AlertTriangle size={21}/></span><div class="grow"><h3>{incident.title}</h3><p class="muted clamp">{incident.summary}</p></div><span class="tag">{titleCase(incident.severity)}</span><button class="button" onclick={()=>navigate('incidents')}>View</button></article>{:else}<div class="empty card compact-empty"><Check size={27}/><h3>No open incidents.</h3><p>New workspace incidents will appear here.</p></div>{/each}</div>
        {:else if page==='documents'}
          {#if !isShared}<div class="toolbar"><label class="inline-label">Project<select bind:value={projectFilter} onchange={loadView}><option value="">All projects</option>{#each projectOptions as p}<option value={p.value}>{p.label}</option>{/each}</select></label></div>{/if}
          {#if canWrite}<form class="upload-panel" onsubmit={upload}><span class="feature-icon"><Upload size={23}/></span><div class="grow"><label for="upload-file"><strong>Add a source document</strong></label><p>TXT, Markdown, CSV, JSON, PDF, or DOCX · Text is extracted on the server.</p><input id="upload-file" bind:this={uploadInput} type="file" accept=".txt,.md,.csv,.json,.pdf,.docx" onchange={e=>uploadFile=e.currentTarget.files?.[0]||null} disabled={busy}/></div><button class="button primary" disabled={!uploadFile||busy}>{busy?'Uploading…':'Upload document'}</button></form>{/if}
          <div class="table-wrap"><table><thead><tr><th>Document</th><th>Type</th><th>Added</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody>{#each rows as doc}<tr><td><button class="file-name" onclick={()=>viewDocument(doc)}><FileText size={21}/><span><strong>{doc.title||doc.filename}</strong><small>{doc.filename}</small></span></button></td><td class="muted">{doc.filename?.split('.').pop()?.toUpperCase()||doc.media_type}</td><td class="muted">{shortDate(doc.created_at)}</td><td><div class="row-actions"><button class="icon-button" aria-label={`Read ${doc.title||doc.filename}`} onclick={()=>viewDocument(doc)}><Eye size={17}/></button>{#if canWrite}<button class="icon-button" aria-label={`Delete ${doc.title||doc.filename}`} disabled={busy} onclick={()=>deleteItem(`/documents/${doc.id}`,'Delete this document and its extracted context?')}><Trash2 size={16}/></button>{/if}</div></td></tr>{:else}<tr><td colspan="4"><div class="empty compact-empty"><FileText size={30}/><h3>No documents in this space.</h3><p>Upload source material to make it available as context.</p></div></td></tr>{/each}</tbody></table></div>
        {:else if page==='chat'}
          {#if !isShared}<div class="toolbar"><label class="inline-label">Project<select bind:value={projectFilter}><option value="">All personal projects</option>{#each projectOptions as p}<option value={p.value}>{p.label}</option>{/each}</select></label></div>{/if}
          {#key `${context}:${projectFilter}`}<AgentChat workspaceId={isShared?context:null} projectId={!isShared?projectFilter:null} models={boot.models||[]} defaultModel={boot.default_model} allowed={cloudAllowed} {canWrite}/>{/key}
        {:else if page==='incidents'}
          <div class="stack">{#each rows as incident}<article class="card incident-card"><header><span class="tag" class:danger={incident.severity==='critical'}>{titleCase(incident.severity)}</span><span class="tag" class:green={incident.status==='resolved'}>{titleCase(incident.status)}</span>{#if incident.published}<span class="tag">Published</span>{/if}{#if incident.escalated}<span class="tag danger">Escalated</span>{/if}<time>{fmt(incident.created_at)}</time></header><h2>{incident.title}</h2><p class="pre-wrap">{incident.summary}</p>{#if incident.decision}<div class="decision"><strong>Decision</strong><p>{incident.decision}</p></div>{/if}{#if incident.resolution}<div class="decision"><strong>Resolution</strong><p>{incident.resolution}</p></div>{/if}<footer><span class="muted">Assigned to {idLabel(incident.assignee_id)}</span><div class="row-actions">{#if canWrite}{#if incident.status==='open'&&(canManage||incident.assignee_id===user.id)}<button class="button" onclick={()=>incidentAction(incident,'acknowledge')}>Acknowledge</button>{/if}{#if incident.status!=='resolved'&&(canManage||incident.assignee_id===user.id)}<button class="button" onclick={()=>incidentAction(incident,'resolve')}>Resolve</button>{/if}{#if !incident.published&&canManage}<button class="button" onclick={()=>incidentAction(incident,'publish')}>Publish summary</button>{/if}{#if incident.severity==='critical'&&incident.published&&!incident.escalated&&canManage}<button class="button" onclick={()=>incidentAction(incident,'escalate')}>Escalate</button>{/if}{/if}</div></footer></article>{:else}<div class="empty card"><AlertTriangle size={30}/><h2>Keep the team informed.</h2><p>Report a workspace incident to coordinate a response.</p>{#if canWrite}<button class="button primary" onclick={()=>incidentForm()}>Report the first incident</button>{/if}</div>{/each}</div>
        {:else if page==='members'}
          <div class="info-strip"><Shield size={20}/><p>Workspace access requires explicit membership and sufficient clearance. Published summary grants are managed separately.</p></div><div class="table-wrap"><table><thead><tr><th>Person</th><th>Role</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody>{#each rows as member}<tr><td><div class="person-cell"><span class="avatar">{member.name?.slice(0,1).toUpperCase()||'U'}</span><span><strong>{member.name||member.user_id}</strong><small>{member.email||''}</small></span></div></td><td><span class="tag">{titleCase(member.role)}</span></td><td>{#if canManage}<div class="row-actions"><label class="sr-only" for={`role-${member.user_id}`}>Role for {member.name||member.user_id}</label><select id={`role-${member.user_id}`} value={member.role} disabled={busy} onchange={e=>act(()=>api(`/workspaces/${context}/members`,{method:'POST',body:{user_id:member.user_id,role:e.currentTarget.value}}),'Membership updated.')}><option value="viewer">Viewer</option><option value="member">Member</option><option value="manager">Manager</option></select><button class="icon-button" aria-label={`Remove ${member.name||member.user_id}`} disabled={busy} onclick={()=>deleteItem(`/workspaces/${context}/members/${member.user_id}`,'Remove this person’s workspace membership?')}><Trash2 size={16}/></button></div>{/if}</td></tr>{/each}</tbody></table></div>
        {:else if page==='jobs'}{#key context}<ScheduledWork workspaceId={isShared?context:null} models={boot.models||[]} defaultModel={boot.default_model} allowed={cloudAllowed} {canWrite} {user}/>{/key}
        {:else if page==='reports'}
          <div class="stack">{#each rows as report}<ReportView {report}/>{:else}<div class="empty card"><BookOpen size={30}/><h2>A place for completed work.</h2><p>Reports appear after scheduled AI jobs finish successfully.</p><button class="button" onclick={()=>navigate('jobs')}>View scheduled work<ArrowRight size={15}/></button></div>{/each}</div>
        {:else if page==='publications'}
          <div class="info-strip"><Shield size={20}/><p>Your grants determine which summaries you can read. Subscriptions control notifications and never expand access.</p></div><div class="stack">{#each rows as publication}<article class="card incident-card"><header><span class="tag">{publication.scope_name||scopeName(publication.scope_id)}</span>{#if publication.severity}<span class="tag" class:danger={publication.severity==='critical'}>{titleCase(publication.severity)}</span>{/if}{#if publication.escalated}<span class="tag danger">Critical escalation</span>{/if}<time>{fmt(publication.created_at)}</time></header><h2>{publication.title}</h2><p class="pre-wrap">{publication.summary}</p>{#if publication.decision}<div class="decision"><strong>Decision</strong><p>{publication.decision}</p></div>{/if}{#if publication.status}<footer><span class="tag">{titleCase(publication.status)}</span></footer>{/if}</article>{:else}<div class="empty card"><Layers size={30}/><h2>No permitted summaries yet.</h2><p>Published summaries appear here when your scope grants authorize access.</p></div>{/each}</div>
        {:else if page==='notifications'}
          <div class="notifications-layout"><div class="stack">{#each rows as notification}<article class="card notification-card" class:unread={!notification.read_at}><span class="feature-icon"><Bell size={19}/></span><div class="grow"><div class="section-heading"><h3>{notification.title}</h3><time>{shortDate(notification.created_at)}</time></div><p>{notification.body}</p><small class="muted">{titleCase(notification.kind)}</small>{#if !notification.read_at}<button class="text-button" disabled={busy} onclick={()=>act(()=>api(`/notifications/${notification.id}/read`,{method:'POST'}),'Notification marked read.')}>Mark as read<Check size={14}/></button>{/if}</div></article>{:else}<div class="empty card"><Bell size={30}/><h2>You’re up to date.</h2><p>Reminder and authorized scope updates will appear here.</p></div>{/each}</div><aside class="card subscriptions"><h2>Scope subscriptions</h2><p>Receive published updates within your existing permissions.</p><form onsubmit={e=>{e.preventDefault();act(()=>api('/subscriptions',{method:'PUT',body:{scope_ids:subscriptionIds}}),'Subscriptions saved.');}}>{#each (boot.scopes||[]).filter(scope=>(boot.reviewable_scope_ids||[]).includes(scope.id)) as scope}<label class="check-row"><input type="checkbox" value={scope.id} bind:group={subscriptionIds} disabled={busy}/><span>{scope.name}<small>{titleCase(scope.kind)}</small></span></label>{:else}<p class="muted">No scopes are available under your current summary grants.</p>{/each}<button class="button wide" disabled={busy}>Save subscriptions</button></form><small class="help">Marking a notification read does not acknowledge an incident.</small></aside></div>
        {:else if page==='admin'&&user.is_admin}
          <div class="admin-tabs"><button class:chosen={adminTab==='users'} onclick={()=>adminTab='users'}><Users size={16}/>Users <span>{rows.length}</span></button><button class:chosen={adminTab==='scopes'} onclick={()=>adminTab='scopes'}><Layers size={16}/>Scopes <span>{adminScopes.length}</span></button><button class:chosen={adminTab==='access'} onclick={()=>adminTab='access'}><Shield size={16}/>Access</button><button class:chosen={adminTab==='delegations'} onclick={()=>adminTab='delegations'}><Users size={16}/>Delegations</button><button class:chosen={adminTab==='integrations'} onclick={()=>adminTab='integrations'}><Zap size={16}/>Integrations</button><button class:chosen={adminTab==='audit'} onclick={()=>adminTab='audit'}><Activity size={16}/>Audit</button></div>
          {#if adminTab==='integrations'}<Connections organization={true} canManage={true} isAdmin={true} workspaces={boot.workspaces||[]}/>{:else if adminTab==='users'}<div class="section-heading"><div><h2>Installation users</h2><p class="muted">Access starts with an active identity and appropriate clearance.</p></div><button class="button primary" onclick={userForm}><Plus size={16}/>Create user</button></div><div class="table-wrap"><table><thead><tr><th>Person</th><th>Clearance</th><th>Status</th><th>Access</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody>{#each rows as u}<tr><td><div class="person-cell"><span class="avatar">{u.name?.slice(0,1).toUpperCase()||'U'}</span><span><strong>{u.name}</strong><small>{u.email}</small></span></div></td><td>{classifications.find(c=>c.value===u.clearance)?.label||u.clearance}</td><td><span class="tag" class:green={u.active}>{u.active?'Active':'Disabled'}</span></td><td>{u.is_admin?'Administrator':'Member'}</td><td><button class="button" onclick={()=>editUser(u)}>Edit</button></td></tr>{/each}</tbody></table></div>
          {:else if adminTab==='scopes'}<div class="section-heading"><div><h2>Organizational structure</h2><p class="muted">Define scopes before creating shared workspaces.</p></div><button class="button primary" onclick={scopeForm}><Plus size={16}/>Create scope</button></div><div class="card-grid">{#each adminScopes as scope}<article class="card scope-card"><span class="feature-icon"><Layers size={23}/></span><span class="tag float-tag">{titleCase(scope.kind)}</span><h2>{scope.name}</h2><p class="muted">{scope.parent_id?`Under ${scopeName(scope.parent_id)}`:'Top-level scope'}</p></article>{:else}<div class="empty card wide-grid"><Layers size={30}/><h2>Define your organization.</h2><p>Create the first scope, such as your enterprise or a site.</p><button class="button primary" onclick={scopeForm}>Create first scope</button></div>{/each}</div>
          {:else if adminTab==='access'}<div class="access-grid"><article class="card access-card"><span class="feature-icon"><Shield size={25}/></span><h2>Published summary grants</h2><p>Grant a user access to published summaries for a scope and its direct children. Explicit critical escalations may reach authorized ancestor scopes.</p><button class="button primary" onclick={grantForm} disabled={!adminScopes.length||!directory.length}><Plus size={16}/>Grant summary access</button></article><article class="card access-card"><span class="feature-icon"><Users size={25}/></span><h2>Shared workspaces</h2><p>Raw documents, conversations, and incidents require explicit workspace membership and sufficient clearance. Administrators do not automatically receive content access.</p><button class="button" onclick={()=>workspaceForm()} disabled={!adminScopes.length}><Plus size={16}/>Create workspace</button></article></div><div class="info-strip"><LockKeyhole size={20}/><p>Private notebooks, memories, conversations, and documents remain owner-only, including for administrators.</p></div><div class="section-heading"><h2>Existing summary grants</h2><span class="muted">{grants.length} grants</span></div><div class="table-wrap"><table><thead><tr><th>Person</th><th>Scope</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody>{#each grants as grant}<tr><td>{idLabel(grant.user_id)}</td><td>{scopeName(grant.scope_id)}</td><td><button class="button" disabled={busy} onclick={()=>deleteItem(`/admin/scope-grants/${grant.user_id}/${grant.scope_id}`,'Revoke this person’s summary access for this scope?')}>Revoke grant</button></td></tr>{:else}<tr><td colspan="3"><div class="empty compact-empty"><Shield size={24}/><p>No published summary grants yet.</p></div></td></tr>{/each}</tbody></table></div>
          {:else if adminTab==='delegations'}<div class="section-heading"><div><h2>Scoped responsibilities</h2><p class="help">Delegate workspace setup and team administration to designated seniors. Membership still controls content access.</p></div><button class="button primary" onclick={delegationForm}><Plus size={15}/>Delegate responsibility</button></div><div class="table-wrap"><table><thead><tr><th>Person</th><th>Scope</th><th>Responsibilities</th><th>Expires</th><th></th></tr></thead><tbody>{#each delegations as delegation}<tr><td>{idLabel(delegation.user_id)}</td><td>{scopeName(delegation.scope_id)}</td><td>{[delegation.manage_workspaces?'Workspace creation':'',delegation.manage_people?'Team management':''].filter(Boolean).join(', ')}</td><td>{delegation.effective_until?fmt(delegation.effective_until):'No expiry'}</td><td><button class="button" onclick={()=>deleteItem(`/admin/delegations/${delegation.id}`,'Revoke this delegated responsibility?')} disabled={busy}>Revoke</button></td></tr>{:else}<tr><td colspan="5">No delegated responsibilities yet.</td></tr>{/each}</tbody></table></div><section class="card hierarchy-editor"><h3>Organizational hierarchy names</h3><p class="help">Use the names your enterprise understands, from broadest to most specific.</p><form onsubmit={e=>{e.preventDefault();act(()=>api('/admin/hierarchy-labels',{method:'PUT',body:{labels:hierarchyLabels}}),'Hierarchy names updated.');}}><label>Hierarchy levels<input value={(Array.isArray(hierarchyLabels)?hierarchyLabels:hierarchyLabels.labels||[]).join(', ')} onchange={e=>hierarchyLabels=e.currentTarget.value.split(',').map(v=>v.trim()).filter(Boolean)} placeholder="enterprise, site, unit, team"/></label><button class="button" disabled={busy}>Save hierarchy names</button></form></section>
          {:else}<div class="section-heading"><h2>Audit activity</h2><span class="muted">Actions and access changes</span></div><div class="table-wrap"><table><thead><tr><th>Action</th><th>Resource</th><th>Actor</th><th>Time</th></tr></thead><tbody>{#each audit as event}<tr><td><strong>{titleCase(event.action)}</strong></td><td>{titleCase(event.resource_type)}<small class="id-text" title={event.resource_id||''}>{event.resource_id?`Ref ${String(event.resource_id).slice(0,8)}`:'—'}</small></td><td>{idLabel(event.actor_id)}</td><td>{fmt(event.created_at)}</td></tr>{:else}<tr><td colspan="4"><div class="empty compact-empty"><Activity size={25}/><p>No audit events yet.</p></div></td></tr>{/each}</tbody></table></div>{/if}
        {/if}
        <footer class="page-footer"><span>V-OptimAIse <span class="dot">·</span> Enterprise workspace</span><span>{isShared?'Shared with explicit members':'Your context, intentionally connected'}</span></footer>
      </main>
    </div>
  </div>
{/if}
{#if modal}<Modal title={modal.title} description={modal.description||''} close={closeModal} busy={modalBusy}>{#if modal.document}<DocumentDetail document={modal.document} {canWrite} saved={loadView}/><div class="form-actions"><button class="button" onclick={closeModal}>Close</button></div>{:else}<EntityForm fields={modal.fields} initial={modal.initial} submit={saveForm} cancel={closeModal} label={modal.label||'Save'} busy={modalBusy} error={modalError}/>{/if}</Modal>{/if}

{#if wizard}<Modal title="Create a shared workspace" description="Start with its purpose and assistant context. Connect sources and invite the team next." close={()=>wizard=false}><WorkspaceWizard scopes={adminScopes.length?adminScopes:boot.scopes||[]} close={()=>wizard=false} saved={async w=>{wizard=false;await refreshBootstrap();await navigate('brief',w.id);}}/></Modal>{/if}
